// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/CurrentPrincipal
type CurrentPrincipal struct {
	Actor                User                                 `json:"actor"`
	Subject              User                                 `json:"subject"`
	AuthenticationMethod CurrentPrincipalAuthenticationMethod `json:"authentication_method"`
	Scopes               []CurrentPrincipalScopesItem         `json:"scopes"`
	Impersonating        bool                                 `json:"impersonating"`
}

// GetActor returns the value of Actor.
func (s *CurrentPrincipal) GetActor() User {
	return s.Actor
}

// GetSubject returns the value of Subject.
func (s *CurrentPrincipal) GetSubject() User {
	return s.Subject
}

// GetAuthenticationMethod returns the value of AuthenticationMethod.
func (s *CurrentPrincipal) GetAuthenticationMethod() CurrentPrincipalAuthenticationMethod {
	return s.AuthenticationMethod
}

// GetScopes returns the value of Scopes.
func (s *CurrentPrincipal) GetScopes() []CurrentPrincipalScopesItem {
	return s.Scopes
}

// GetImpersonating returns the value of Impersonating.
func (s *CurrentPrincipal) GetImpersonating() bool {
	return s.Impersonating
}

// SetActor sets the value of Actor.
func (s *CurrentPrincipal) SetActor(val User) {
	s.Actor = val
}

// SetSubject sets the value of Subject.
func (s *CurrentPrincipal) SetSubject(val User) {
	s.Subject = val
}

// SetAuthenticationMethod sets the value of AuthenticationMethod.
func (s *CurrentPrincipal) SetAuthenticationMethod(val CurrentPrincipalAuthenticationMethod) {
	s.AuthenticationMethod = val
}

// SetScopes sets the value of Scopes.
func (s *CurrentPrincipal) SetScopes(val []CurrentPrincipalScopesItem) {
	s.Scopes = val
}

// SetImpersonating sets the value of Impersonating.
func (s *CurrentPrincipal) SetImpersonating(val bool) {
	s.Impersonating = val
}

func (*CurrentPrincipal) getCurrentPrincipalRes() {}

type CurrentPrincipalAuthenticationMethod string

const (
	CurrentPrincipalAuthenticationMethodSession  CurrentPrincipalAuthenticationMethod = "session"
	CurrentPrincipalAuthenticationMethodAPIToken CurrentPrincipalAuthenticationMethod = "api_token"
)

// AllValues returns all CurrentPrincipalAuthenticationMethod values.
func (CurrentPrincipalAuthenticationMethod) AllValues() []CurrentPrincipalAuthenticationMethod {
	return []CurrentPrincipalAuthenticationMethod{
		CurrentPrincipalAuthenticationMethodSession,
		CurrentPrincipalAuthenticationMethodAPIToken,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CurrentPrincipalAuthenticationMethod) MarshalText() ([]byte, error) {
	switch s {
	case CurrentPrincipalAuthenticationMethodSession:
		return []byte(s), nil
	case CurrentPrincipalAuthenticationMethodAPIToken:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CurrentPrincipalAuthenticationMethod) UnmarshalText(data []byte) error {
	switch CurrentPrincipalAuthenticationMethod(data) {
	case CurrentPrincipalAuthenticationMethodSession:
		*s = CurrentPrincipalAuthenticationMethodSession
		return nil
	case CurrentPrincipalAuthenticationMethodAPIToken:
		*s = CurrentPrincipalAuthenticationMethodAPIToken
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CurrentPrincipalScopesItem string

const (
	CurrentPrincipalScopesItemWorkRead  CurrentPrincipalScopesItem = "work:read"
	CurrentPrincipalScopesItemWorkWrite CurrentPrincipalScopesItem = "work:write"
)

// AllValues returns all CurrentPrincipalScopesItem values.
func (CurrentPrincipalScopesItem) AllValues() []CurrentPrincipalScopesItem {
	return []CurrentPrincipalScopesItem{
		CurrentPrincipalScopesItemWorkRead,
		CurrentPrincipalScopesItemWorkWrite,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CurrentPrincipalScopesItem) MarshalText() ([]byte, error) {
	switch s {
	case CurrentPrincipalScopesItemWorkRead:
		return []byte(s), nil
	case CurrentPrincipalScopesItemWorkWrite:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CurrentPrincipalScopesItem) UnmarshalText(data []byte) error {
	switch CurrentPrincipalScopesItem(data) {
	case CurrentPrincipalScopesItemWorkRead:
		*s = CurrentPrincipalScopesItemWorkRead
		return nil
	case CurrentPrincipalScopesItemWorkWrite:
		*s = CurrentPrincipalScopesItemWorkWrite
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Problem
type Problem struct {
	Type      string  `json:"type"`
	Title     string  `json:"title"`
	Status    int     `json:"status"`
	Detail    string  `json:"detail"`
	Code      string  `json:"code"`
	RequestID string  `json:"request_id"`
	Retryable OptBool `json:"retryable"`
}

// GetType returns the value of Type.
func (s *Problem) GetType() string {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *Problem) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Problem) GetStatus() int {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *Problem) GetDetail() string {
	return s.Detail
}

// GetCode returns the value of Code.
func (s *Problem) GetCode() string {
	return s.Code
}

// GetRequestID returns the value of RequestID.
func (s *Problem) GetRequestID() string {
	return s.RequestID
}

// GetRetryable returns the value of Retryable.
func (s *Problem) GetRetryable() OptBool {
	return s.Retryable
}

// SetType sets the value of Type.
func (s *Problem) SetType(val string) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *Problem) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Problem) SetStatus(val int) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *Problem) SetDetail(val string) {
	s.Detail = val
}

// SetCode sets the value of Code.
func (s *Problem) SetCode(val string) {
	s.Code = val
}

// SetRequestID sets the value of RequestID.
func (s *Problem) SetRequestID(val string) {
	s.RequestID = val
}

// SetRetryable sets the value of Retryable.
func (s *Problem) SetRetryable(val OptBool) {
	s.Retryable = val
}

// ProblemStatusCode wraps Problem with StatusCode.
type ProblemStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ProblemStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ProblemStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ProblemStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ProblemStatusCode) SetResponse(val Problem) {
	s.Response = val
}

func (*ProblemStatusCode) getCurrentPrincipalRes() {}
func (*ProblemStatusCode) listUsersRes()           {}

type SessionCookie struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *SessionCookie) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *SessionCookie) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *SessionCookie) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *SessionCookie) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/User
type User struct {
	ID           uuid.UUID        `json:"id"`
	Name         string           `json:"name"`
	Email        OptString        `json:"email"`
	AvatarURL    OptURI           `json:"avatar_url"`
	PlatformRole UserPlatformRole `json:"platform_role"`
	Active       bool             `json:"active"`
}

// GetID returns the value of ID.
func (s *User) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() OptString {
	return s.Email
}

// GetAvatarURL returns the value of AvatarURL.
func (s *User) GetAvatarURL() OptURI {
	return s.AvatarURL
}

// GetPlatformRole returns the value of PlatformRole.
func (s *User) GetPlatformRole() UserPlatformRole {
	return s.PlatformRole
}

// GetActive returns the value of Active.
func (s *User) GetActive() bool {
	return s.Active
}

// SetID sets the value of ID.
func (s *User) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val OptString) {
	s.Email = val
}

// SetAvatarURL sets the value of AvatarURL.
func (s *User) SetAvatarURL(val OptURI) {
	s.AvatarURL = val
}

// SetPlatformRole sets the value of PlatformRole.
func (s *User) SetPlatformRole(val UserPlatformRole) {
	s.PlatformRole = val
}

// SetActive sets the value of Active.
func (s *User) SetActive(val bool) {
	s.Active = val
}

// Ref: #/components/schemas/UserList
type UserList struct {
	Items      []User    `json:"items"`
	NextCursor OptString `json:"next_cursor"`
}

// GetItems returns the value of Items.
func (s *UserList) GetItems() []User {
	return s.Items
}

// GetNextCursor returns the value of NextCursor.
func (s *UserList) GetNextCursor() OptString {
	return s.NextCursor
}

// SetItems sets the value of Items.
func (s *UserList) SetItems(val []User) {
	s.Items = val
}

// SetNextCursor sets the value of NextCursor.
func (s *UserList) SetNextCursor(val OptString) {
	s.NextCursor = val
}

func (*UserList) listUsersRes() {}

type UserPlatformRole string

const (
	UserPlatformRoleADMIN  UserPlatformRole = "ADMIN"
	UserPlatformRoleMEMBER UserPlatformRole = "MEMBER"
)

// AllValues returns all UserPlatformRole values.
func (UserPlatformRole) AllValues() []UserPlatformRole {
	return []UserPlatformRole{
		UserPlatformRoleADMIN,
		UserPlatformRoleMEMBER,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UserPlatformRole) MarshalText() ([]byte, error) {
	switch s {
	case UserPlatformRoleADMIN:
		return []byte(s), nil
	case UserPlatformRoleMEMBER:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UserPlatformRole) UnmarshalText(data []byte) error {
	switch UserPlatformRole(data) {
	case UserPlatformRoleADMIN:
		*s = UserPlatformRoleADMIN
		return nil
	case UserPlatformRoleMEMBER:
		*s = UserPlatformRoleMEMBER
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
