// Code generated by ogen, DO NOT EDIT.
package api

type AcceptTaskRes interface {
	acceptTaskRes()
}

type ActivateMilestoneRes interface {
	activateMilestoneRes()
}

type AddProjectMemberRes interface {
	addProjectMemberRes()
}

type ArchiveProjectRes interface {
	archiveProjectRes()
}

type ArchiveTaskRes interface {
	archiveTaskRes()
}

type BindProjectRepositoryRes interface {
	bindProjectRepositoryRes()
}

type CancelMilestoneRes interface {
	cancelMilestoneRes()
}

type CancelTaskRes interface {
	cancelTaskRes()
}

type CompleteMilestoneRes interface {
	completeMilestoneRes()
}

type CompleteTaskAttachmentUploadRes interface {
	completeTaskAttachmentUploadRes()
}

type CompleteTaskExecutionRes interface {
	completeTaskExecutionRes()
}

type CreateAcceptanceCheckRes interface {
	createAcceptanceCheckRes()
}

type CreateLabelRes interface {
	createLabelRes()
}

type CreateMilestoneCriterionRes interface {
	createMilestoneCriterionRes()
}

type CreateMilestoneRes interface {
	createMilestoneRes()
}

type CreateProjectRes interface {
	createProjectRes()
}

type CreateTaskAttachmentUploadRes interface {
	createTaskAttachmentUploadRes()
}

type CreateTaskCriterionRes interface {
	createTaskCriterionRes()
}

type CreateTaskRes interface {
	createTaskRes()
}

type CreateTaskStageClaimRes interface {
	createTaskStageClaimRes()
}

type CreateTaskThreadMessageRes interface {
	createTaskThreadMessageRes()
}

type DeleteCriterionRes interface {
	deleteCriterionRes()
}

type DeleteLabelRes interface {
	deleteLabelRes()
}

type DeleteTaskAttachmentRes interface {
	deleteTaskAttachmentRes()
}

type DeleteTaskThreadMessageRes interface {
	deleteTaskThreadMessageRes()
}

type GetAgentConversationRes interface {
	getAgentConversationRes()
}

type GetClaimWorkPacketRes interface {
	getClaimWorkPacketRes()
}

type GetCurrentAgentConversationConfigurationRes interface {
	getCurrentAgentConversationConfigurationRes()
}

type GetCurrentPrincipalRes interface {
	getCurrentPrincipalRes()
}

type GetProjectRes interface {
	getProjectRes()
}

type GetTaskAttachmentContentRes interface {
	getTaskAttachmentContentRes()
}

type GetTaskDeliveryRes interface {
	getTaskDeliveryRes()
}

type GetTaskRes interface {
	getTaskRes()
}

type GetTaskStageClaimRes interface {
	getTaskStageClaimRes()
}

type GetTaskWorkPacketRes interface {
	getTaskWorkPacketRes()
}

type LinkTaskCodeChangeRes interface {
	linkTaskCodeChangeRes()
}

type ListAgentConversationsRes interface {
	listAgentConversationsRes()
}

type ListLabelsRes interface {
	listLabelsRes()
}

type ListMilestoneCriteriaRes interface {
	listMilestoneCriteriaRes()
}

type ListOwnedTaskStageClaimsRes interface {
	listOwnedTaskStageClaimsRes()
}

type ListProjectMembersRes interface {
	listProjectMembersRes()
}

type ListProjectRepositoriesRes interface {
	listProjectRepositoriesRes()
}

type ListProjectsRes interface {
	listProjectsRes()
}

type ListTaskActivityRes interface {
	listTaskActivityRes()
}

type ListTaskAttachmentsRes interface {
	listTaskAttachmentsRes()
}

type ListTaskCriteriaRes interface {
	listTaskCriteriaRes()
}

type ListTaskStageClaimsRes interface {
	listTaskStageClaimsRes()
}

type ListTaskThreadItemsRes interface {
	listTaskThreadItemsRes()
}

type ListTaskThreadsRes interface {
	listTaskThreadsRes()
}

type ListTasksRes interface {
	listTasksRes()
}

type ListUsersRes interface {
	listUsersRes()
}

type MarkTaskReadyRes interface {
	markTaskReadyRes()
}

type RecordTaskClaimProgressRes interface {
	recordTaskClaimProgressRes()
}

type RecordTaskStageAcceptanceCheckRes interface {
	recordTaskStageAcceptanceCheckRes()
}

type RecordTaskWorkSubmissionRes interface {
	recordTaskWorkSubmissionRes()
}

type ReleaseTaskStageClaimRes interface {
	releaseTaskStageClaimRes()
}

type RemoveProjectMemberRes interface {
	removeProjectMemberRes()
}

type ReopenMilestoneRes interface {
	reopenMilestoneRes()
}

type RequestTaskChangesRes interface {
	requestTaskChangesRes()
}

type RequestTaskResolutionRes interface {
	requestTaskResolutionRes()
}

type ResolveTaskIssueRes interface {
	resolveTaskIssueRes()
}

type RestoreProjectRes interface {
	restoreProjectRes()
}

type RestoreTaskRes interface {
	restoreTaskRes()
}

type UnbindProjectRepositoryRes interface {
	unbindProjectRepositoryRes()
}

type UnlinkTaskCodeChangeRes interface {
	unlinkTaskCodeChangeRes()
}

type UpdateAgentConversationRes interface {
	updateAgentConversationRes()
}

type UpdateCriterionRes interface {
	updateCriterionRes()
}

type UpdateCurrentAgentConversationConfigurationRes interface {
	updateCurrentAgentConversationConfigurationRes()
}

type UpdateLabelRes interface {
	updateLabelRes()
}

type UpdateMilestoneRes interface {
	updateMilestoneRes()
}

type UpdateProjectMemberRes interface {
	updateProjectMemberRes()
}

type UpdateProjectRes interface {
	updateProjectRes()
}

type UpdateTaskRes interface {
	updateTaskRes()
}

type UpdateTaskThreadMessageRes interface {
	updateTaskThreadMessageRes()
}

type UploadTaskAttachmentContentRes interface {
	uploadTaskAttachmentContentRes()
}

type WithdrawTaskReadinessRes interface {
	withdrawTaskReadinessRes()
}
