// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetCurrentPrincipal implements getCurrentPrincipal operation.
//
// Get the authenticated principal.
//
// GET /api/v1/me
func (UnimplementedHandler) GetCurrentPrincipal(ctx context.Context) (r GetCurrentPrincipalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUsers implements listUsers operation.
//
// List users available for work assignment.
//
// GET /api/v1/users
func (UnimplementedHandler) ListUsers(ctx context.Context) (r ListUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}
