// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetCurrentPrincipal implements getCurrentPrincipal operation.
	//
	// Get the authenticated principal.
	//
	// GET /api/v1/me
	GetCurrentPrincipal(ctx context.Context) (GetCurrentPrincipalRes, error)
	// ListUsers implements listUsers operation.
	//
	// List users available for work assignment.
	//
	// GET /api/v1/users
	ListUsers(ctx context.Context) (ListUsersRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
