// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AcceptTask implements acceptTask operation.
//
// Accept the Task outcome and complete the Task.
//
// POST /api/v1/claims/{claim_id}/accept
func (UnimplementedHandler) AcceptTask(ctx context.Context, req *TaskStageClaimFinish, params AcceptTaskParams) (r AcceptTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActivateMilestone implements activateMilestone operation.
//
// Activate a planned milestone.
//
// POST /api/v1/projects/{number}/milestones/{id}/activate
func (UnimplementedHandler) ActivateMilestone(ctx context.Context, params ActivateMilestoneParams) (r ActivateMilestoneRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddProjectMember implements addProjectMember operation.
//
// Add a Project member.
//
// POST /api/v1/projects/{number}/members
func (UnimplementedHandler) AddProjectMember(ctx context.Context, req *ProjectMembershipCreate, params AddProjectMemberParams) (r AddProjectMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ArchiveProject implements archiveProject operation.
//
// Archive a project.
//
// POST /api/v1/projects/{number}/archive
func (UnimplementedHandler) ArchiveProject(ctx context.Context, params ArchiveProjectParams) (r ArchiveProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ArchiveTask implements archiveTask operation.
//
// Archive a task.
//
// POST /api/v1/tasks/{number}/archive
func (UnimplementedHandler) ArchiveTask(ctx context.Context, params ArchiveTaskParams) (r ArchiveTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BindProjectRepository implements bindProjectRepository operation.
//
// Bind a GitLab repository to a Project by URL.
//
// POST /api/v1/projects/{number}/repositories
func (UnimplementedHandler) BindProjectRepository(ctx context.Context, req *ProjectRepositoryBind, params BindProjectRepositoryParams) (r BindProjectRepositoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CancelMilestone implements cancelMilestone operation.
//
// Cancel a milestone.
//
// POST /api/v1/projects/{number}/milestones/{id}/cancel
func (UnimplementedHandler) CancelMilestone(ctx context.Context, req OptLifecycleRequest, params CancelMilestoneParams) (r CancelMilestoneRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CancelTask implements cancelTask operation.
//
// Cancel a non-terminal Task and close active workflow state.
//
// POST /api/v1/tasks/{number}/commands/cancel
func (UnimplementedHandler) CancelTask(ctx context.Context, req *ReasonWrite, params CancelTaskParams) (r CancelTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompleteMilestone implements completeMilestone operation.
//
// Complete a milestone.
//
// POST /api/v1/projects/{number}/milestones/{id}/complete
func (UnimplementedHandler) CompleteMilestone(ctx context.Context, req OptLifecycleRequest, params CompleteMilestoneParams) (r CompleteMilestoneRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompleteTaskAttachmentUpload implements completeTaskAttachmentUpload operation.
//
// Verify an uploaded object and create the Task attachment.
//
// POST /api/v1/tasks/{number}/attachments/uploads/{id}/complete
func (UnimplementedHandler) CompleteTaskAttachmentUpload(ctx context.Context, params CompleteTaskAttachmentUploadParams) (r CompleteTaskAttachmentUploadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompleteTaskExecution implements completeTaskExecution operation.
//
// End execution and make the frozen delivery available for review.
//
// POST /api/v1/claims/{claim_id}/complete-execution
func (UnimplementedHandler) CompleteTaskExecution(ctx context.Context, req *TaskStageClaimFinish, params CompleteTaskExecutionParams) (r CompleteTaskExecutionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAcceptanceCheck implements createAcceptanceCheck operation.
//
// Record an immutable acceptance check.
//
// POST /api/v1/criteria/{id}/checks
func (UnimplementedHandler) CreateAcceptanceCheck(ctx context.Context, req *AcceptanceCheckCreate, params CreateAcceptanceCheckParams) (r CreateAcceptanceCheckRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateLabel implements createLabel operation.
//
// Create a label.
//
// POST /api/v1/labels
func (UnimplementedHandler) CreateLabel(ctx context.Context, req *LabelWrite, params CreateLabelParams) (r CreateLabelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMilestone implements createMilestone operation.
//
// Create a milestone.
//
// POST /api/v1/projects/{number}/milestones
func (UnimplementedHandler) CreateMilestone(ctx context.Context, req *MilestoneCreate, params CreateMilestoneParams) (r CreateMilestoneRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMilestoneCriterion implements createMilestoneCriterion operation.
//
// Create a milestone acceptance criterion.
//
// POST /api/v1/projects/{number}/milestones/{id}/criteria
func (UnimplementedHandler) CreateMilestoneCriterion(ctx context.Context, req *CriterionCreate, params CreateMilestoneCriterionParams) (r CreateMilestoneCriterionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProject implements createProject operation.
//
// Create a project.
//
// POST /api/v1/projects
func (UnimplementedHandler) CreateProject(ctx context.Context, req *ProjectCreate, params CreateProjectParams) (r CreateProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTask implements createTask operation.
//
// Create a task.
//
// POST /api/v1/tasks
func (UnimplementedHandler) CreateTask(ctx context.Context, req *TaskCreate, params CreateTaskParams) (r CreateTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTaskAttachmentUpload implements createTaskAttachmentUpload operation.
//
// Create a private attachment upload session.
//
// POST /api/v1/tasks/{number}/attachments/uploads
func (UnimplementedHandler) CreateTaskAttachmentUpload(ctx context.Context, req *TaskAttachmentUploadWrite, params CreateTaskAttachmentUploadParams) (r CreateTaskAttachmentUploadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTaskCriterion implements createTaskCriterion operation.
//
// Create a task acceptance criterion.
//
// POST /api/v1/tasks/{number}/criteria
func (UnimplementedHandler) CreateTaskCriterion(ctx context.Context, req *CriterionCreate, params CreateTaskCriterionParams) (r CreateTaskCriterionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTaskStageClaim implements createTaskStageClaim operation.
//
// Claim the Task's currently available execution or review stage.
//
// POST /api/v1/tasks/{number}/claims
func (UnimplementedHandler) CreateTaskStageClaim(ctx context.Context, params CreateTaskStageClaimParams) (r CreateTaskStageClaimRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTaskThreadMessage implements createTaskThreadMessage operation.
//
// Add an ordinary message or immutable progress update to one Task Thread.
//
// POST /api/v1/threads/{id}/items
func (UnimplementedHandler) CreateTaskThreadMessage(ctx context.Context, req *TaskThreadMessageWrite, params CreateTaskThreadMessageParams) (r CreateTaskThreadMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCriterion implements deleteCriterion operation.
//
// Remove an acceptance criterion.
//
// DELETE /api/v1/criteria/{id}
func (UnimplementedHandler) DeleteCriterion(ctx context.Context, req OptLifecycleRequest, params DeleteCriterionParams) (r DeleteCriterionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteLabel implements deleteLabel operation.
//
// Delete a label.
//
// DELETE /api/v1/labels/{id}
func (UnimplementedHandler) DeleteLabel(ctx context.Context, params DeleteLabelParams) (r DeleteLabelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTaskAttachment implements deleteTaskAttachment operation.
//
// Soft-delete a Task attachment.
//
// DELETE /api/v1/tasks/{number}/attachments/{id}
func (UnimplementedHandler) DeleteTaskAttachment(ctx context.Context, params DeleteTaskAttachmentParams) (r DeleteTaskAttachmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTaskThreadMessage implements deleteTaskThreadMessage operation.
//
// Delete a message owned by the caller.
//
// DELETE /api/v1/thread-items/{id}
func (UnimplementedHandler) DeleteTaskThreadMessage(ctx context.Context, params DeleteTaskThreadMessageParams) (r DeleteTaskThreadMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgentConversation implements getAgentConversation operation.
//
// Get an Agent conversation configuration.
//
// GET /api/v1/agent-conversations/{id}
func (UnimplementedHandler) GetAgentConversation(ctx context.Context, params GetAgentConversationParams) (r GetAgentConversationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetClaimWorkPacket implements getClaimWorkPacket operation.
//
// Get bounded authoritative context for one explicit Claim.
//
// GET /api/v1/claims/{claim_id}/work-packet
func (UnimplementedHandler) GetClaimWorkPacket(ctx context.Context, params GetClaimWorkPacketParams) (r GetClaimWorkPacketRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentAgentConversationConfiguration implements getCurrentAgentConversationConfiguration operation.
//
// Get the conversation configuration bound to the authenticated Agent Run.
//
// GET /api/v1/agent-runs/current/conversation-configuration
func (UnimplementedHandler) GetCurrentAgentConversationConfiguration(ctx context.Context) (r GetCurrentAgentConversationConfigurationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentPrincipal implements getCurrentPrincipal operation.
//
// Get the authenticated principal.
//
// GET /api/v1/me
func (UnimplementedHandler) GetCurrentPrincipal(ctx context.Context) (r GetCurrentPrincipalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProject implements getProject operation.
//
// Get a project and its work aggregate.
//
// GET /api/v1/projects/{number}
func (UnimplementedHandler) GetProject(ctx context.Context, params GetProjectParams) (r GetProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTask implements getTask operation.
//
// Get a task.
//
// GET /api/v1/tasks/{number}
func (UnimplementedHandler) GetTask(ctx context.Context, params GetTaskParams) (r GetTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTaskAttachmentContent implements getTaskAttachmentContent operation.
//
// Read authorized private attachment content.
//
// GET /api/v1/tasks/{number}/attachments/{id}/content
func (UnimplementedHandler) GetTaskAttachmentContent(ctx context.Context, params GetTaskAttachmentContentParams) (r GetTaskAttachmentContentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTaskDelivery implements getTaskDelivery operation.
//
// Get active and frozen Task merge-request delivery state.
//
// GET /api/v1/tasks/{number}/merge-requests
func (UnimplementedHandler) GetTaskDelivery(ctx context.Context, params GetTaskDeliveryParams) (r GetTaskDeliveryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTaskStageClaim implements getTaskStageClaim operation.
//
// Get one Claim by its globally unique ID.
//
// GET /api/v1/claims/{claim_id}
func (UnimplementedHandler) GetTaskStageClaim(ctx context.Context, params GetTaskStageClaimParams) (r GetTaskStageClaimRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTaskWorkPacket implements getTaskWorkPacket operation.
//
// Get bounded authoritative context for a Task before claiming it.
//
// GET /api/v1/tasks/{number}/work-packet
func (UnimplementedHandler) GetTaskWorkPacket(ctx context.Context, params GetTaskWorkPacketParams) (r GetTaskWorkPacketRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LinkTaskMergeRequest implements linkTaskMergeRequest operation.
//
// Link a GitLab merge request during claimed execution.
//
// POST /api/v1/claims/{claim_id}/merge-requests
func (UnimplementedHandler) LinkTaskMergeRequest(ctx context.Context, req *TaskMergeRequestLink, params LinkTaskMergeRequestParams) (r LinkTaskMergeRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAgentConversations implements listAgentConversations operation.
//
// List visible Agent conversation configurations.
//
// GET /api/v1/agent-conversations
func (UnimplementedHandler) ListAgentConversations(ctx context.Context) (r ListAgentConversationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListLabels implements listLabels operation.
//
// List labels.
//
// GET /api/v1/labels
func (UnimplementedHandler) ListLabels(ctx context.Context, params ListLabelsParams) (r ListLabelsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMilestoneCriteria implements listMilestoneCriteria operation.
//
// List milestone acceptance criteria.
//
// GET /api/v1/projects/{number}/milestones/{id}/criteria
func (UnimplementedHandler) ListMilestoneCriteria(ctx context.Context, params ListMilestoneCriteriaParams) (r ListMilestoneCriteriaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOwnedTaskStageClaims implements listOwnedTaskStageClaims operation.
//
// List Claims owned by the authenticated logical principal.
//
// GET /api/v1/claims
func (UnimplementedHandler) ListOwnedTaskStageClaims(ctx context.Context, params ListOwnedTaskStageClaimsParams) (r ListOwnedTaskStageClaimsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProjectMembers implements listProjectMembers operation.
//
// List Project members.
//
// GET /api/v1/projects/{number}/members
func (UnimplementedHandler) ListProjectMembers(ctx context.Context, params ListProjectMembersParams) (r ListProjectMembersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProjectRepositories implements listProjectRepositories operation.
//
// List repositories authorized for a Project.
//
// GET /api/v1/projects/{number}/repositories
func (UnimplementedHandler) ListProjectRepositories(ctx context.Context, params ListProjectRepositoriesParams) (r ListProjectRepositoriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProjects implements listProjects operation.
//
// List projects.
//
// GET /api/v1/projects
func (UnimplementedHandler) ListProjects(ctx context.Context, params ListProjectsParams) (r ListProjectsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTaskActivity implements listTaskActivity operation.
//
// List task activity.
//
// GET /api/v1/tasks/{number}/activity
func (UnimplementedHandler) ListTaskActivity(ctx context.Context, params ListTaskActivityParams) (r ListTaskActivityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTaskAttachments implements listTaskAttachments operation.
//
// List active Task attachments.
//
// GET /api/v1/tasks/{number}/attachments
func (UnimplementedHandler) ListTaskAttachments(ctx context.Context, params ListTaskAttachmentsParams) (r ListTaskAttachmentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTaskCriteria implements listTaskCriteria operation.
//
// List task acceptance criteria.
//
// GET /api/v1/tasks/{number}/criteria
func (UnimplementedHandler) ListTaskCriteria(ctx context.Context, params ListTaskCriteriaParams) (r ListTaskCriteriaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTaskStageClaims implements listTaskStageClaims operation.
//
// List execution and acceptance Claims for a Task.
//
// GET /api/v1/tasks/{number}/claims
func (UnimplementedHandler) ListTaskStageClaims(ctx context.Context, params ListTaskStageClaimsParams) (r ListTaskStageClaimsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTaskThreadItems implements listTaskThreadItems operation.
//
// List Items in one Task Thread.
//
// GET /api/v1/threads/{id}/items
func (UnimplementedHandler) ListTaskThreadItems(ctx context.Context, params ListTaskThreadItemsParams) (r ListTaskThreadItemsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTaskThreads implements listTaskThreads operation.
//
// List the Main Thread and historical Issue Threads.
//
// GET /api/v1/tasks/{number}/threads
func (UnimplementedHandler) ListTaskThreads(ctx context.Context, params ListTaskThreadsParams) (r ListTaskThreadsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTasks implements listTasks operation.
//
// List tasks.
//
// GET /api/v1/tasks
func (UnimplementedHandler) ListTasks(ctx context.Context, params ListTasksParams) (r ListTasksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUsers implements listUsers operation.
//
// List users available for work assignment.
//
// GET /api/v1/users
func (UnimplementedHandler) ListUsers(ctx context.Context, params ListUsersParams) (r ListUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MarkTaskReady implements markTaskReady operation.
//
// Mark a backlog Task ready to claim.
//
// POST /api/v1/tasks/{number}/commands/mark-ready
func (UnimplementedHandler) MarkTaskReady(ctx context.Context, params MarkTaskReadyParams) (r MarkTaskReadyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RecordTaskClaimProgress implements recordTaskClaimProgress operation.
//
// Append immutable progress to the Claim's Main Thread.
//
// POST /api/v1/claims/{claim_id}/progress
func (UnimplementedHandler) RecordTaskClaimProgress(ctx context.Context, req *BodyWrite, params RecordTaskClaimProgressParams) (r RecordTaskClaimProgressRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RecordTaskStageAcceptanceCheck implements recordTaskStageAcceptanceCheck operation.
//
// Record execution verification or acceptance through the active Claim.
//
// POST /api/v1/claims/{claim_id}/criteria/{criterion_id}/checks
func (UnimplementedHandler) RecordTaskStageAcceptanceCheck(ctx context.Context, req *TaskStageAcceptanceCheckWrite, params RecordTaskStageAcceptanceCheckParams) (r RecordTaskStageAcceptanceCheckRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RecordTaskWorkSubmission implements recordTaskWorkSubmission operation.
//
// Record an immutable work submission without ending execution.
//
// POST /api/v1/claims/{claim_id}/submissions
func (UnimplementedHandler) RecordTaskWorkSubmission(ctx context.Context, req *TaskStageClaimFinish, params RecordTaskWorkSubmissionParams) (r RecordTaskWorkSubmissionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReleaseTaskStageClaim implements releaseTaskStageClaim operation.
//
// Release the active Claim with a durable handoff.
//
// POST /api/v1/claims/{claim_id}/release
func (UnimplementedHandler) ReleaseTaskStageClaim(ctx context.Context, req *TaskStageClaimFinish, params ReleaseTaskStageClaimParams) (r ReleaseTaskStageClaimRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveProjectMember implements removeProjectMember operation.
//
// Remove a Project member.
//
// DELETE /api/v1/projects/{number}/members/{user_id}
func (UnimplementedHandler) RemoveProjectMember(ctx context.Context, params RemoveProjectMemberParams) (r RemoveProjectMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReopenMilestone implements reopenMilestone operation.
//
// Reopen a milestone.
//
// POST /api/v1/projects/{number}/milestones/{id}/reopen
func (UnimplementedHandler) ReopenMilestone(ctx context.Context, req *LifecycleRequest, params ReopenMilestoneParams) (r ReopenMilestoneRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RequestTaskChanges implements requestTaskChanges operation.
//
// Return acceptance review to execution.
//
// POST /api/v1/claims/{claim_id}/request-changes
func (UnimplementedHandler) RequestTaskChanges(ctx context.Context, req *TaskStageClaimFinish, params RequestTaskChangesParams) (r RequestTaskChangesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RequestTaskResolution implements requestTaskResolution operation.
//
// End the Claim and open one typed blocking Issue Thread.
//
// POST /api/v1/claims/{claim_id}/request-resolution
func (UnimplementedHandler) RequestTaskResolution(ctx context.Context, req *TaskResolutionRequest, params RequestTaskResolutionParams) (r RequestTaskResolutionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResolveTaskIssue implements resolveTaskIssue operation.
//
// Resolve the active Issue and return the Task to available.
//
// POST /api/v1/tasks/{number}/issues/{id}/resolve
func (UnimplementedHandler) ResolveTaskIssue(ctx context.Context, req *TaskIssueResolve, params ResolveTaskIssueParams) (r ResolveTaskIssueRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RestoreProject implements restoreProject operation.
//
// Restore a project.
//
// POST /api/v1/projects/{number}/restore
func (UnimplementedHandler) RestoreProject(ctx context.Context, params RestoreProjectParams) (r RestoreProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RestoreTask implements restoreTask operation.
//
// Restore a task.
//
// POST /api/v1/tasks/{number}/restore
func (UnimplementedHandler) RestoreTask(ctx context.Context, params RestoreTaskParams) (r RestoreTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UnbindProjectRepository implements unbindProjectRepository operation.
//
// Unbind a GitLab repository from a Project.
//
// DELETE /api/v1/projects/{number}/repositories/{repository_id}
func (UnimplementedHandler) UnbindProjectRepository(ctx context.Context, params UnbindProjectRepositoryParams) (r UnbindProjectRepositoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UnlinkTaskMergeRequest implements unlinkTaskMergeRequest operation.
//
// Unlink a GitLab merge request during claimed execution.
//
// DELETE /api/v1/claims/{claim_id}/merge-requests/{link_id}
func (UnimplementedHandler) UnlinkTaskMergeRequest(ctx context.Context, params UnlinkTaskMergeRequestParams) (r UnlinkTaskMergeRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAgentConversation implements updateAgentConversation operation.
//
// Update an Agent conversation configuration.
//
// PATCH /api/v1/agent-conversations/{id}
func (UnimplementedHandler) UpdateAgentConversation(ctx context.Context, req *AgentConversationPatch, params UpdateAgentConversationParams) (r UpdateAgentConversationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCriterion implements updateCriterion operation.
//
// Update an acceptance criterion.
//
// PATCH /api/v1/criteria/{id}
func (UnimplementedHandler) UpdateCriterion(ctx context.Context, req *CriterionPatch, params UpdateCriterionParams) (r UpdateCriterionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCurrentAgentConversationConfiguration implements updateCurrentAgentConversationConfiguration operation.
//
// Update the conversation configuration bound to the authenticated Agent Run.
//
// PATCH /api/v1/agent-runs/current/conversation-configuration
func (UnimplementedHandler) UpdateCurrentAgentConversationConfiguration(ctx context.Context, req *AgentConversationPatch, params UpdateCurrentAgentConversationConfigurationParams) (r UpdateCurrentAgentConversationConfigurationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateLabel implements updateLabel operation.
//
// Rename a label.
//
// PATCH /api/v1/labels/{id}
func (UnimplementedHandler) UpdateLabel(ctx context.Context, req *LabelWrite, params UpdateLabelParams) (r UpdateLabelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMilestone implements updateMilestone operation.
//
// Update a milestone.
//
// PATCH /api/v1/projects/{number}/milestones/{id}
func (UnimplementedHandler) UpdateMilestone(ctx context.Context, req *MilestonePatch, params UpdateMilestoneParams) (r UpdateMilestoneRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProject implements updateProject operation.
//
// Update a project.
//
// PATCH /api/v1/projects/{number}
func (UnimplementedHandler) UpdateProject(ctx context.Context, req *ProjectPatch, params UpdateProjectParams) (r UpdateProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProjectMember implements updateProjectMember operation.
//
// Change a Project member role.
//
// PATCH /api/v1/projects/{number}/members/{user_id}
func (UnimplementedHandler) UpdateProjectMember(ctx context.Context, req *ProjectMembershipPatch, params UpdateProjectMemberParams) (r UpdateProjectMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTask implements updateTask operation.
//
// Update a task.
//
// PATCH /api/v1/tasks/{number}
func (UnimplementedHandler) UpdateTask(ctx context.Context, req *TaskPatch, params UpdateTaskParams) (r UpdateTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTaskThreadMessage implements updateTaskThreadMessage operation.
//
// Edit a message owned by the caller.
//
// PATCH /api/v1/thread-items/{id}
func (UnimplementedHandler) UpdateTaskThreadMessage(ctx context.Context, req *TaskThreadMessageUpdate, params UpdateTaskThreadMessageParams) (r UpdateTaskThreadMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadTaskAttachmentContent implements uploadTaskAttachmentContent operation.
//
// Stream content into a Local storage upload session.
//
// PUT /api/v1/tasks/{number}/attachments/uploads/{id}/content
func (UnimplementedHandler) UploadTaskAttachmentContent(ctx context.Context, req UploadTaskAttachmentContentReq, params UploadTaskAttachmentContentParams) (r UploadTaskAttachmentContentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WithdrawTaskReadiness implements withdrawTaskReadiness operation.
//
// Return a ready Task to backlog.
//
// POST /api/v1/tasks/{number}/commands/withdraw-readiness
func (UnimplementedHandler) WithdrawTaskReadiness(ctx context.Context, req *ReasonWrite, params WithdrawTaskReadinessParams) (r WithdrawTaskReadinessRes, _ error) {
	return r, ht.ErrNotImplemented
}
