// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearerAuth handles bearerAuth security.
	HandleBearerAuth(ctx context.Context, operationName OperationName, t BearerAuth) (context.Context, error)
	// HandleSessionCookie handles sessionCookie security.
	HandleSessionCookie(ctx context.Context, operationName OperationName, t SessionCookie) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	AcceptTaskOperation:                                  []string{},
	ActivateMilestoneOperation:                           []string{},
	AddProjectMemberOperation:                            []string{},
	ArchiveProjectOperation:                              []string{},
	ArchiveTaskOperation:                                 []string{},
	CancelMilestoneOperation:                             []string{},
	CancelTaskOperation:                                  []string{},
	CompleteMilestoneOperation:                           []string{},
	CompleteTaskAttachmentUploadOperation:                []string{},
	CompleteTaskExecutionOperation:                       []string{},
	CreateAcceptanceCheckOperation:                       []string{},
	CreateLabelOperation:                                 []string{},
	CreateMilestoneOperation:                             []string{},
	CreateMilestoneCriterionOperation:                    []string{},
	CreateProjectOperation:                               []string{},
	CreateTaskOperation:                                  []string{},
	CreateTaskAttachmentUploadOperation:                  []string{},
	CreateTaskCriterionOperation:                         []string{},
	CreateTaskStageClaimOperation:                        []string{},
	CreateTaskThreadMessageOperation:                     []string{},
	DeleteCriterionOperation:                             []string{},
	DeleteLabelOperation:                                 []string{},
	DeleteTaskAttachmentOperation:                        []string{},
	DeleteTaskThreadMessageOperation:                     []string{},
	GetAgentConversationOperation:                        []string{},
	GetCurrentAgentConversationConfigurationOperation:    []string{},
	GetCurrentPrincipalOperation:                         []string{},
	GetCurrentTaskStageClaimOperation:                    []string{},
	GetProjectOperation:                                  []string{},
	GetTaskOperation:                                     []string{},
	GetTaskAttachmentContentOperation:                    []string{},
	GetTaskDeliveryOperation:                             []string{},
	LinkTaskMergeRequestOperation:                        []string{},
	ListAgentConversationsOperation:                      []string{},
	ListLabelsOperation:                                  []string{},
	ListMilestoneCriteriaOperation:                       []string{},
	ListProjectMembersOperation:                          []string{},
	ListProjectRepositoriesOperation:                     []string{},
	ListProjectsOperation:                                []string{},
	ListTaskActivityOperation:                            []string{},
	ListTaskAttachmentsOperation:                         []string{},
	ListTaskCriteriaOperation:                            []string{},
	ListTaskStageClaimsOperation:                         []string{},
	ListTaskThreadItemsOperation:                         []string{},
	ListTaskThreadsOperation:                             []string{},
	ListTasksOperation:                                   []string{},
	ListUsersOperation:                                   []string{},
	MarkTaskReadyOperation:                               []string{},
	RecordTaskStageAcceptanceCheckOperation:              []string{},
	RecordTaskWorkSubmissionOperation:                    []string{},
	ReleaseTaskStageClaimOperation:                       []string{},
	RemoveProjectMemberOperation:                         []string{},
	ReopenMilestoneOperation:                             []string{},
	RequestTaskChangesOperation:                          []string{},
	RequestTaskResolutionOperation:                       []string{},
	ResolveTaskIssueOperation:                            []string{},
	RestoreProjectOperation:                              []string{},
	RestoreTaskOperation:                                 []string{},
	UnlinkTaskMergeRequestOperation:                      []string{},
	UpdateAgentConversationOperation:                     []string{},
	UpdateCriterionOperation:                             []string{},
	UpdateCurrentAgentConversationConfigurationOperation: []string{},
	UpdateLabelOperation:                                 []string{},
	UpdateMilestoneOperation:                             []string{},
	UpdateProjectOperation:                               []string{},
	UpdateProjectMemberOperation:                         []string{},
	UpdateTaskOperation:                                  []string{},
	UpdateTaskThreadMessageOperation:                     []string{},
	UploadTaskAttachmentContentOperation:                 []string{},
	WithdrawTaskReadinessOperation:                       []string{},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesSessionCookie is a private map storing roles per operation.
var operationRolesSessionCookie = map[string][]string{
	AcceptTaskOperation:                     []string{},
	ActivateMilestoneOperation:              []string{},
	AddProjectMemberOperation:               []string{},
	ArchiveProjectOperation:                 []string{},
	ArchiveTaskOperation:                    []string{},
	BindProjectRepositoryOperation:          []string{},
	CancelMilestoneOperation:                []string{},
	CancelTaskOperation:                     []string{},
	CompleteMilestoneOperation:              []string{},
	CompleteTaskAttachmentUploadOperation:   []string{},
	CompleteTaskExecutionOperation:          []string{},
	CreateAcceptanceCheckOperation:          []string{},
	CreateLabelOperation:                    []string{},
	CreateMilestoneOperation:                []string{},
	CreateMilestoneCriterionOperation:       []string{},
	CreateProjectOperation:                  []string{},
	CreateTaskOperation:                     []string{},
	CreateTaskAttachmentUploadOperation:     []string{},
	CreateTaskCriterionOperation:            []string{},
	CreateTaskStageClaimOperation:           []string{},
	CreateTaskThreadMessageOperation:        []string{},
	DeleteCriterionOperation:                []string{},
	DeleteLabelOperation:                    []string{},
	DeleteTaskAttachmentOperation:           []string{},
	DeleteTaskThreadMessageOperation:        []string{},
	GetAgentConversationOperation:           []string{},
	GetCurrentPrincipalOperation:            []string{},
	GetCurrentTaskStageClaimOperation:       []string{},
	GetProjectOperation:                     []string{},
	GetTaskOperation:                        []string{},
	GetTaskAttachmentContentOperation:       []string{},
	GetTaskDeliveryOperation:                []string{},
	LinkTaskMergeRequestOperation:           []string{},
	ListAgentConversationsOperation:         []string{},
	ListLabelsOperation:                     []string{},
	ListMilestoneCriteriaOperation:          []string{},
	ListProjectMembersOperation:             []string{},
	ListProjectRepositoriesOperation:        []string{},
	ListProjectsOperation:                   []string{},
	ListTaskActivityOperation:               []string{},
	ListTaskAttachmentsOperation:            []string{},
	ListTaskCriteriaOperation:               []string{},
	ListTaskStageClaimsOperation:            []string{},
	ListTaskThreadItemsOperation:            []string{},
	ListTaskThreadsOperation:                []string{},
	ListTasksOperation:                      []string{},
	ListUsersOperation:                      []string{},
	MarkTaskReadyOperation:                  []string{},
	RecordTaskStageAcceptanceCheckOperation: []string{},
	RecordTaskWorkSubmissionOperation:       []string{},
	ReleaseTaskStageClaimOperation:          []string{},
	RemoveProjectMemberOperation:            []string{},
	ReopenMilestoneOperation:                []string{},
	RequestTaskChangesOperation:             []string{},
	RequestTaskResolutionOperation:          []string{},
	ResolveTaskIssueOperation:               []string{},
	RestoreProjectOperation:                 []string{},
	RestoreTaskOperation:                    []string{},
	UnbindProjectRepositoryOperation:        []string{},
	UnlinkTaskMergeRequestOperation:         []string{},
	UpdateAgentConversationOperation:        []string{},
	UpdateCriterionOperation:                []string{},
	UpdateLabelOperation:                    []string{},
	UpdateMilestoneOperation:                []string{},
	UpdateProjectOperation:                  []string{},
	UpdateProjectMemberOperation:            []string{},
	UpdateTaskOperation:                     []string{},
	UpdateTaskThreadMessageOperation:        []string{},
	UploadTaskAttachmentContentOperation:    []string{},
	WithdrawTaskReadinessOperation:          []string{},
}

// GetRolesForSessionCookie returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForSessionCookie(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForSessionCookie(operation string) []string {
	roles, ok := operationRolesSessionCookie[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuth[operationName]
	rctx, err := s.sec.HandleBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securitySessionCookie(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t SessionCookie
	const parameterName = "bb_session"
	var value string
	switch cookie, err := req.Cookie(parameterName); {
	case err == nil: // if NO error
		value = cookie.Value
	case errors.Is(err, http.ErrNoCookie):
		return ctx, false, nil
	default:
		return nil, false, errors.Wrap(err, "get cookie value")
	}
	t.APIKey = value
	t.Roles = operationRolesSessionCookie[operationName]
	rctx, err := s.sec.HandleSessionCookie(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides bearerAuth security value.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
	// SessionCookie provides sessionCookie security value.
	SessionCookie(ctx context.Context, operationName OperationName) (SessionCookie, error)
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securitySessionCookie(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.SessionCookie(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"SessionCookie\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "bb_session",
		Value: t.APIKey,
	})
	return nil
}
