// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn52AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn10AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn13AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn20AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn61AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn50AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn57AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn11AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key",
	}
	rn62AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn68AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn33AllowedHeaders = map[string]string{
		"DELETE": "Authorization,Content-Type,Idempotency-Key,If-Match",
		"PATCH":  "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn34AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn35AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type,Idempotency-Key",
	}
	rn45AllowedHeaders = map[string]string{
		"DELETE": "Authorization,Idempotency-Key,If-Match",
		"PATCH":  "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn51AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn38AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type,Idempotency-Key",
	}
	rn2AllowedHeaders = map[string]string{
		"GET":   "Authorization",
		"PATCH": "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn15AllowedHeaders = map[string]string{
		"POST": "Authorization,Idempotency-Key,If-Match",
	}
	rn7AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn64AllowedHeaders = map[string]string{
		"DELETE": "Authorization,Idempotency-Key,If-Match",
		"PATCH":  "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn36AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn4AllowedHeaders = map[string]string{
		"PATCH": "Authorization,Content-Type,Idempotency-Key,If-Match,X-Project-If-Match",
	}
	rn5AllowedHeaders = map[string]string{
		"POST": "Authorization,Idempotency-Key,If-Match,X-Project-If-Match",
	}
	rn22AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match,X-Project-If-Match",
	}
	rn26AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match,X-Project-If-Match",
	}
	rn37AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match,X-Project-If-Match",
	}
	rn65AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match,X-Project-If-Match",
	}
	rn66AllowedHeaders = map[string]string{
		"POST": "Authorization,Idempotency-Key,If-Match",
	}
	rn39AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type,Idempotency-Key",
	}
	rn17AllowedHeaders = map[string]string{
		"GET":   "Authorization",
		"PATCH": "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn54AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn55AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn18AllowedHeaders = map[string]string{
		"POST": "Authorization,Idempotency-Key,If-Match",
	}
	rn56AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn40AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key",
	}
	rn30AllowedHeaders = map[string]string{
		"POST": "Authorization,Idempotency-Key,If-Match",
	}
	rn70AllowedHeaders = map[string]string{
		"PUT": "Authorization,Content-Type",
	}
	rn47AllowedHeaders = map[string]string{
		"DELETE": "Authorization,Idempotency-Key,If-Match",
	}
	rn53AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn24AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type,Idempotency-Key",
	}
	rn42AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn49AllowedHeaders = map[string]string{
		"DELETE": "Authorization,Idempotency-Key,If-Match",
		"PATCH":  "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn43AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type,Idempotency-Key,If-Match",
	}
	rn67AllowedHeaders = map[string]string{
		"POST": "Authorization,Idempotency-Key,If-Match",
	}
	rn58AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [2]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/v1/"

			if l := len("/api/v1/"); len(elem) >= l && elem[0:l] == "/api/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "agent/claims/current"

				if l := len("agent/claims/current"); len(elem) >= l && elem[0:l] == "agent/claims/current" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetCurrentTaskClaimRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: rn52AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'c': // Prefix: "c"

				if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'l': // Prefix: "laims/"

					if l := len("laims/"); len(elem) >= l && elem[0:l] == "laims/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetTaskClaimRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn10AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "a"

							if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'n': // Prefix: "nswer"

								if l := len("nswer"); len(elem) >= l && elem[0:l] == "nswer" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleAnswerTaskClaimQuestionRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn13AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							case 's': // Prefix: "sk"

								if l := len("sk"); len(elem) >= l && elem[0:l] == "sk" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleAskTaskClaimQuestionRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn20AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'c': // Prefix: "criteria/"

							if l := len("criteria/"); len(elem) >= l && elem[0:l] == "criteria/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "criterion_id"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[1] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case '/': // Prefix: "/checks"

								if l := len("/checks"); len(elem) >= l && elem[0:l] == "/checks" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleRecordTaskClaimAcceptanceCheckRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn61AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'e': // Prefix: "extend"

							if l := len("extend"); len(elem) >= l && elem[0:l] == "extend" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleExtendTaskClaimRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn50AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'm': // Prefix: "messages"

							if l := len("messages"); len(elem) >= l && elem[0:l] == "messages" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListTaskClaimMessagesRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn57AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'p': // Prefix: "progress"

							if l := len("progress"); len(elem) >= l && elem[0:l] == "progress" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleAddTaskClaimProgressRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn11AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'r': // Prefix: "release"

							if l := len("release"); len(elem) >= l && elem[0:l] == "release" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleReleaseTaskClaimRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn62AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 's': // Prefix: "submit"

							if l := len("submit"); len(elem) >= l && elem[0:l] == "submit" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleSubmitTaskClaimRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn68AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				case 'r': // Prefix: "riteria/"

					if l := len("riteria/"); len(elem) >= l && elem[0:l] == "riteria/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "DELETE":
							s.handleDeleteCriterionRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PATCH":
							s.handleUpdateCriterionRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,PATCH",
								allowedHeaders: rn33AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "application/json",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/checks"

						if l := len("/checks"); len(elem) >= l && elem[0:l] == "/checks" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleCreateAcceptanceCheckRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn34AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'l': // Prefix: "labels"

				if l := len("labels"); len(elem) >= l && elem[0:l] == "labels" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListLabelsRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateLabelRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn35AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleDeleteLabelRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PATCH":
							s.handleUpdateLabelRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,PATCH",
								allowedHeaders: rn45AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "application/json",
							})
						}

						return
					}

				}

			case 'm': // Prefix: "me"

				if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetCurrentPrincipalRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: rn51AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'p': // Prefix: "projects"

				if l := len("projects"); len(elem) >= l && elem[0:l] == "projects" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListProjectsRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateProjectRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn38AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "number"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetProjectRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PATCH":
							s.handleUpdateProjectRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,PATCH",
								allowedHeaders: rn2AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "application/json",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "archive"

							if l := len("archive"); len(elem) >= l && elem[0:l] == "archive" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleArchiveProjectRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn15AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'm': // Prefix: "m"

							if l := len("m"); len(elem) >= l && elem[0:l] == "m" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'e': // Prefix: "embers"

								if l := len("embers"); len(elem) >= l && elem[0:l] == "embers" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch r.Method {
									case "GET":
										s.handleListProjectMembersRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									case "POST":
										s.handleAddProjectMemberRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET,POST",
											allowedHeaders: rn7AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "user_id"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "DELETE":
											s.handleRemoveProjectMemberRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										case "PATCH":
											s.handleUpdateProjectMemberRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "DELETE,PATCH",
												allowedHeaders: rn64AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "application/json",
											})
										}

										return
									}

								}

							case 'i': // Prefix: "ilestones"

								if l := len("ilestones"); len(elem) >= l && elem[0:l] == "ilestones" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch r.Method {
									case "POST":
										s.handleCreateMilestoneRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn36AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "id"
									// Match until "/"
									idx := strings.IndexByte(elem, '/')
									if idx < 0 {
										idx = len(elem)
									}
									args[1] = elem[:idx]
									elem = elem[idx:]

									if len(elem) == 0 {
										switch r.Method {
										case "PATCH":
											s.handleUpdateMilestoneRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "PATCH",
												allowedHeaders: rn4AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "application/json",
											})
										}

										return
									}
									switch elem[0] {
									case '/': // Prefix: "/"

										if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'a': // Prefix: "activate"

											if l := len("activate"); len(elem) >= l && elem[0:l] == "activate" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "POST":
													s.handleActivateMilestoneRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, notAllowedParams{
														allowedMethods: "POST",
														allowedHeaders: rn5AllowedHeaders,
														acceptPost:     "",
														acceptPatch:    "",
													})
												}

												return
											}

										case 'c': // Prefix: "c"

											if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												break
											}
											switch elem[0] {
											case 'a': // Prefix: "ancel"

												if l := len("ancel"); len(elem) >= l && elem[0:l] == "ancel" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													// Leaf node.
													switch r.Method {
													case "POST":
														s.handleCancelMilestoneRequest([2]string{
															args[0],
															args[1],
														}, elemIsEscaped, w, r)
													default:
														s.notAllowed(w, r, notAllowedParams{
															allowedMethods: "POST",
															allowedHeaders: rn22AllowedHeaders,
															acceptPost:     "application/json",
															acceptPatch:    "",
														})
													}

													return
												}

											case 'o': // Prefix: "omplete"

												if l := len("omplete"); len(elem) >= l && elem[0:l] == "omplete" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													// Leaf node.
													switch r.Method {
													case "POST":
														s.handleCompleteMilestoneRequest([2]string{
															args[0],
															args[1],
														}, elemIsEscaped, w, r)
													default:
														s.notAllowed(w, r, notAllowedParams{
															allowedMethods: "POST",
															allowedHeaders: rn26AllowedHeaders,
															acceptPost:     "application/json",
															acceptPatch:    "",
														})
													}

													return
												}

											case 'r': // Prefix: "riteria"

												if l := len("riteria"); len(elem) >= l && elem[0:l] == "riteria" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													// Leaf node.
													switch r.Method {
													case "GET":
														s.handleListMilestoneCriteriaRequest([2]string{
															args[0],
															args[1],
														}, elemIsEscaped, w, r)
													case "POST":
														s.handleCreateMilestoneCriterionRequest([2]string{
															args[0],
															args[1],
														}, elemIsEscaped, w, r)
													default:
														s.notAllowed(w, r, notAllowedParams{
															allowedMethods: "GET,POST",
															allowedHeaders: rn37AllowedHeaders,
															acceptPost:     "application/json",
															acceptPatch:    "",
														})
													}

													return
												}

											}

										case 'r': // Prefix: "reopen"

											if l := len("reopen"); len(elem) >= l && elem[0:l] == "reopen" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "POST":
													s.handleReopenMilestoneRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, notAllowedParams{
														allowedMethods: "POST",
														allowedHeaders: rn65AllowedHeaders,
														acceptPost:     "application/json",
														acceptPatch:    "",
													})
												}

												return
											}

										}

									}

								}

							}

						case 'r': // Prefix: "restore"

							if l := len("restore"); len(elem) >= l && elem[0:l] == "restore" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleRestoreProjectRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn66AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			case 't': // Prefix: "tasks"

				if l := len("tasks"); len(elem) >= l && elem[0:l] == "tasks" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListTasksRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateTaskRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn39AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "number"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetTaskRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PATCH":
							s.handleUpdateTaskRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,PATCH",
								allowedHeaders: rn17AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "application/json",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "a"

							if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'c': // Prefix: "ctivity"

								if l := len("ctivity"); len(elem) >= l && elem[0:l] == "ctivity" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleListTaskActivityRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn54AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'g': // Prefix: "gent-conversations"

								if l := len("gent-conversations"); len(elem) >= l && elem[0:l] == "gent-conversations" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleListTaskAgentConversationsRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn55AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'r': // Prefix: "rchive"

								if l := len("rchive"); len(elem) >= l && elem[0:l] == "rchive" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleArchiveTaskRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn18AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 't': // Prefix: "ttachments"

								if l := len("ttachments"); len(elem) >= l && elem[0:l] == "ttachments" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch r.Method {
									case "GET":
										s.handleListTaskAttachmentsRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn56AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'u': // Prefix: "uploads"
										origElem := elem
										if l := len("uploads"); len(elem) >= l && elem[0:l] == "uploads" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch r.Method {
											case "POST":
												s.handleCreateTaskAttachmentUploadRequest([1]string{
													args[0],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "POST",
													allowedHeaders: rn40AllowedHeaders,
													acceptPost:     "application/json",
													acceptPatch:    "",
												})
											}

											return
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "id"
											// Match until "/"
											idx := strings.IndexByte(elem, '/')
											if idx < 0 {
												idx = len(elem)
											}
											args[1] = elem[:idx]
											elem = elem[idx:]

											if len(elem) == 0 {
												break
											}
											switch elem[0] {
											case '/': // Prefix: "/co"

												if l := len("/co"); len(elem) >= l && elem[0:l] == "/co" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													break
												}
												switch elem[0] {
												case 'm': // Prefix: "mplete"

													if l := len("mplete"); len(elem) >= l && elem[0:l] == "mplete" {
														elem = elem[l:]
													} else {
														break
													}

													if len(elem) == 0 {
														// Leaf node.
														switch r.Method {
														case "POST":
															s.handleCompleteTaskAttachmentUploadRequest([2]string{
																args[0],
																args[1],
															}, elemIsEscaped, w, r)
														default:
															s.notAllowed(w, r, notAllowedParams{
																allowedMethods: "POST",
																allowedHeaders: rn30AllowedHeaders,
																acceptPost:     "",
																acceptPatch:    "",
															})
														}

														return
													}

												case 'n': // Prefix: "ntent"

													if l := len("ntent"); len(elem) >= l && elem[0:l] == "ntent" {
														elem = elem[l:]
													} else {
														break
													}

													if len(elem) == 0 {
														// Leaf node.
														switch r.Method {
														case "PUT":
															s.handleUploadTaskAttachmentContentRequest([2]string{
																args[0],
																args[1],
															}, elemIsEscaped, w, r)
														default:
															s.notAllowed(w, r, notAllowedParams{
																allowedMethods: "PUT",
																allowedHeaders: rn70AllowedHeaders,
																acceptPost:     "",
																acceptPatch:    "",
															})
														}

														return
													}

												}

											}

										}

										elem = origElem
									}
									// Param: "id"
									// Match until "/"
									idx := strings.IndexByte(elem, '/')
									if idx < 0 {
										idx = len(elem)
									}
									args[1] = elem[:idx]
									elem = elem[idx:]

									if len(elem) == 0 {
										switch r.Method {
										case "DELETE":
											s.handleDeleteTaskAttachmentRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "DELETE",
												allowedHeaders: rn47AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}
									switch elem[0] {
									case '/': // Prefix: "/content"

										if l := len("/content"); len(elem) >= l && elem[0:l] == "/content" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "GET":
												s.handleGetTaskAttachmentContentRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "GET",
													allowedHeaders: rn53AllowedHeaders,
													acceptPost:     "",
													acceptPatch:    "",
												})
											}

											return
										}

									}

								}

							}

						case 'c': // Prefix: "c"

							if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'l': // Prefix: "laim"

								if l := len("laim"); len(elem) >= l && elem[0:l] == "laim" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleClaimTaskRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn24AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'o': // Prefix: "omments"

								if l := len("omments"); len(elem) >= l && elem[0:l] == "omments" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch r.Method {
									case "GET":
										s.handleListTaskCommentsRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									case "POST":
										s.handleCreateTaskCommentRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET,POST",
											allowedHeaders: rn42AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "id"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "DELETE":
											s.handleDeleteTaskCommentRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										case "PATCH":
											s.handleUpdateTaskCommentRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "DELETE,PATCH",
												allowedHeaders: rn49AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "application/json",
											})
										}

										return
									}

								}

							case 'r': // Prefix: "riteria"

								if l := len("riteria"); len(elem) >= l && elem[0:l] == "riteria" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleListTaskCriteriaRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									case "POST":
										s.handleCreateTaskCriterionRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET,POST",
											allowedHeaders: rn43AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'r': // Prefix: "restore"

							if l := len("restore"); len(elem) >= l && elem[0:l] == "restore" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleRestoreTaskRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn67AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			case 'u': // Prefix: "users"

				if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleListUsersRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: rn58AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [2]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/v1/"

			if l := len("/api/v1/"); len(elem) >= l && elem[0:l] == "/api/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "agent/claims/current"

				if l := len("agent/claims/current"); len(elem) >= l && elem[0:l] == "agent/claims/current" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetCurrentTaskClaimOperation
						r.summary = "Get the unfinished Claim owned by this client session"
						r.operationID = "getCurrentTaskClaim"
						r.operationGroup = ""
						r.pathPattern = "/api/v1/agent/claims/current"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'c': // Prefix: "c"

				if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'l': // Prefix: "laims/"

					if l := len("laims/"); len(elem) >= l && elem[0:l] == "laims/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetTaskClaimOperation
							r.summary = "Get a Claim"
							r.operationID = "getTaskClaim"
							r.operationGroup = ""
							r.pathPattern = "/api/v1/claims/{id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "a"

							if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'n': // Prefix: "nswer"

								if l := len("nswer"); len(elem) >= l && elem[0:l] == "nswer" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = AnswerTaskClaimQuestionOperation
										r.summary = "Answer the pending Agent question and resume the Claim"
										r.operationID = "answerTaskClaimQuestion"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/claims/{id}/answer"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 's': // Prefix: "sk"

								if l := len("sk"); len(elem) >= l && elem[0:l] == "sk" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = AskTaskClaimQuestionOperation
										r.summary = "Ask a human question and pause the Claim"
										r.operationID = "askTaskClaimQuestion"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/claims/{id}/ask"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						case 'c': // Prefix: "criteria/"

							if l := len("criteria/"); len(elem) >= l && elem[0:l] == "criteria/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "criterion_id"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[1] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case '/': // Prefix: "/checks"

								if l := len("/checks"); len(elem) >= l && elem[0:l] == "/checks" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = RecordTaskClaimAcceptanceCheckOperation
										r.summary = "Record an acceptance check owned by the active Claim"
										r.operationID = "recordTaskClaimAcceptanceCheck"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/claims/{id}/criteria/{criterion_id}/checks"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							}

						case 'e': // Prefix: "extend"

							if l := len("extend"); len(elem) >= l && elem[0:l] == "extend" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ExtendTaskClaimOperation
									r.summary = "Extend an active Claim"
									r.operationID = "extendTaskClaim"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/claims/{id}/extend"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'm': // Prefix: "messages"

							if l := len("messages"); len(elem) >= l && elem[0:l] == "messages" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListTaskClaimMessagesOperation
									r.summary = "List the immutable Agent conversation for a Claim"
									r.operationID = "listTaskClaimMessages"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/claims/{id}/messages"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'p': // Prefix: "progress"

							if l := len("progress"); len(elem) >= l && elem[0:l] == "progress" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = AddTaskClaimProgressOperation
									r.summary = "Add an Agent progress message"
									r.operationID = "addTaskClaimProgress"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/claims/{id}/progress"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'r': // Prefix: "release"

							if l := len("release"); len(elem) >= l && elem[0:l] == "release" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ReleaseTaskClaimOperation
									r.summary = "Release a Claim"
									r.operationID = "releaseTaskClaim"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/claims/{id}/release"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 's': // Prefix: "submit"

							if l := len("submit"); len(elem) >= l && elem[0:l] == "submit" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = SubmitTaskClaimOperation
									r.summary = "Submit verified Agent work for human review"
									r.operationID = "submitTaskClaim"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/claims/{id}/submit"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				case 'r': // Prefix: "riteria/"

					if l := len("riteria/"); len(elem) >= l && elem[0:l] == "riteria/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "DELETE":
							r.name = DeleteCriterionOperation
							r.summary = "Remove an acceptance criterion"
							r.operationID = "deleteCriterion"
							r.operationGroup = ""
							r.pathPattern = "/api/v1/criteria/{id}"
							r.args = args
							r.count = 1
							return r, true
						case "PATCH":
							r.name = UpdateCriterionOperation
							r.summary = "Update an acceptance criterion"
							r.operationID = "updateCriterion"
							r.operationGroup = ""
							r.pathPattern = "/api/v1/criteria/{id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/checks"

						if l := len("/checks"); len(elem) >= l && elem[0:l] == "/checks" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = CreateAcceptanceCheckOperation
								r.summary = "Record an immutable acceptance check"
								r.operationID = "createAcceptanceCheck"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/criteria/{id}/checks"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'l': // Prefix: "labels"

				if l := len("labels"); len(elem) >= l && elem[0:l] == "labels" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListLabelsOperation
						r.summary = "List labels"
						r.operationID = "listLabels"
						r.operationGroup = ""
						r.pathPattern = "/api/v1/labels"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateLabelOperation
						r.summary = "Create a label"
						r.operationID = "createLabel"
						r.operationGroup = ""
						r.pathPattern = "/api/v1/labels"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = DeleteLabelOperation
							r.summary = "Delete a label"
							r.operationID = "deleteLabel"
							r.operationGroup = ""
							r.pathPattern = "/api/v1/labels/{id}"
							r.args = args
							r.count = 1
							return r, true
						case "PATCH":
							r.name = UpdateLabelOperation
							r.summary = "Rename a label"
							r.operationID = "updateLabel"
							r.operationGroup = ""
							r.pathPattern = "/api/v1/labels/{id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 'm': // Prefix: "me"

				if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetCurrentPrincipalOperation
						r.summary = "Get the authenticated principal"
						r.operationID = "getCurrentPrincipal"
						r.operationGroup = ""
						r.pathPattern = "/api/v1/me"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'p': // Prefix: "projects"

				if l := len("projects"); len(elem) >= l && elem[0:l] == "projects" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListProjectsOperation
						r.summary = "List projects"
						r.operationID = "listProjects"
						r.operationGroup = ""
						r.pathPattern = "/api/v1/projects"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateProjectOperation
						r.summary = "Create a project"
						r.operationID = "createProject"
						r.operationGroup = ""
						r.pathPattern = "/api/v1/projects"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "number"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetProjectOperation
							r.summary = "Get a project and its work aggregate"
							r.operationID = "getProject"
							r.operationGroup = ""
							r.pathPattern = "/api/v1/projects/{number}"
							r.args = args
							r.count = 1
							return r, true
						case "PATCH":
							r.name = UpdateProjectOperation
							r.summary = "Update a project"
							r.operationID = "updateProject"
							r.operationGroup = ""
							r.pathPattern = "/api/v1/projects/{number}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "archive"

							if l := len("archive"); len(elem) >= l && elem[0:l] == "archive" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ArchiveProjectOperation
									r.summary = "Archive a project"
									r.operationID = "archiveProject"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/projects/{number}/archive"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'm': // Prefix: "m"

							if l := len("m"); len(elem) >= l && elem[0:l] == "m" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'e': // Prefix: "embers"

								if l := len("embers"); len(elem) >= l && elem[0:l] == "embers" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch method {
									case "GET":
										r.name = ListProjectMembersOperation
										r.summary = "List Project members"
										r.operationID = "listProjectMembers"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/projects/{number}/members"
										r.args = args
										r.count = 1
										return r, true
									case "POST":
										r.name = AddProjectMemberOperation
										r.summary = "Add a Project member"
										r.operationID = "addProjectMember"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/projects/{number}/members"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "user_id"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "DELETE":
											r.name = RemoveProjectMemberOperation
											r.summary = "Remove a Project member"
											r.operationID = "removeProjectMember"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/projects/{number}/members/{user_id}"
											r.args = args
											r.count = 2
											return r, true
										case "PATCH":
											r.name = UpdateProjectMemberOperation
											r.summary = "Change a Project member role"
											r.operationID = "updateProjectMember"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/projects/{number}/members/{user_id}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

								}

							case 'i': // Prefix: "ilestones"

								if l := len("ilestones"); len(elem) >= l && elem[0:l] == "ilestones" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch method {
									case "POST":
										r.name = CreateMilestoneOperation
										r.summary = "Create a milestone"
										r.operationID = "createMilestone"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/projects/{number}/milestones"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "id"
									// Match until "/"
									idx := strings.IndexByte(elem, '/')
									if idx < 0 {
										idx = len(elem)
									}
									args[1] = elem[:idx]
									elem = elem[idx:]

									if len(elem) == 0 {
										switch method {
										case "PATCH":
											r.name = UpdateMilestoneOperation
											r.summary = "Update a milestone"
											r.operationID = "updateMilestone"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/projects/{number}/milestones/{id}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}
									switch elem[0] {
									case '/': // Prefix: "/"

										if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'a': // Prefix: "activate"

											if l := len("activate"); len(elem) >= l && elem[0:l] == "activate" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "POST":
													r.name = ActivateMilestoneOperation
													r.summary = "Activate a planned milestone"
													r.operationID = "activateMilestone"
													r.operationGroup = ""
													r.pathPattern = "/api/v1/projects/{number}/milestones/{id}/activate"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

										case 'c': // Prefix: "c"

											if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												break
											}
											switch elem[0] {
											case 'a': // Prefix: "ancel"

												if l := len("ancel"); len(elem) >= l && elem[0:l] == "ancel" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													// Leaf node.
													switch method {
													case "POST":
														r.name = CancelMilestoneOperation
														r.summary = "Cancel a milestone"
														r.operationID = "cancelMilestone"
														r.operationGroup = ""
														r.pathPattern = "/api/v1/projects/{number}/milestones/{id}/cancel"
														r.args = args
														r.count = 2
														return r, true
													default:
														return
													}
												}

											case 'o': // Prefix: "omplete"

												if l := len("omplete"); len(elem) >= l && elem[0:l] == "omplete" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													// Leaf node.
													switch method {
													case "POST":
														r.name = CompleteMilestoneOperation
														r.summary = "Complete a milestone"
														r.operationID = "completeMilestone"
														r.operationGroup = ""
														r.pathPattern = "/api/v1/projects/{number}/milestones/{id}/complete"
														r.args = args
														r.count = 2
														return r, true
													default:
														return
													}
												}

											case 'r': // Prefix: "riteria"

												if l := len("riteria"); len(elem) >= l && elem[0:l] == "riteria" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													// Leaf node.
													switch method {
													case "GET":
														r.name = ListMilestoneCriteriaOperation
														r.summary = "List milestone acceptance criteria"
														r.operationID = "listMilestoneCriteria"
														r.operationGroup = ""
														r.pathPattern = "/api/v1/projects/{number}/milestones/{id}/criteria"
														r.args = args
														r.count = 2
														return r, true
													case "POST":
														r.name = CreateMilestoneCriterionOperation
														r.summary = "Create a milestone acceptance criterion"
														r.operationID = "createMilestoneCriterion"
														r.operationGroup = ""
														r.pathPattern = "/api/v1/projects/{number}/milestones/{id}/criteria"
														r.args = args
														r.count = 2
														return r, true
													default:
														return
													}
												}

											}

										case 'r': // Prefix: "reopen"

											if l := len("reopen"); len(elem) >= l && elem[0:l] == "reopen" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "POST":
													r.name = ReopenMilestoneOperation
													r.summary = "Reopen a milestone"
													r.operationID = "reopenMilestone"
													r.operationGroup = ""
													r.pathPattern = "/api/v1/projects/{number}/milestones/{id}/reopen"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

										}

									}

								}

							}

						case 'r': // Prefix: "restore"

							if l := len("restore"); len(elem) >= l && elem[0:l] == "restore" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = RestoreProjectOperation
									r.summary = "Restore a project"
									r.operationID = "restoreProject"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/projects/{number}/restore"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			case 't': // Prefix: "tasks"

				if l := len("tasks"); len(elem) >= l && elem[0:l] == "tasks" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListTasksOperation
						r.summary = "List tasks"
						r.operationID = "listTasks"
						r.operationGroup = ""
						r.pathPattern = "/api/v1/tasks"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateTaskOperation
						r.summary = "Create a task"
						r.operationID = "createTask"
						r.operationGroup = ""
						r.pathPattern = "/api/v1/tasks"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "number"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetTaskOperation
							r.summary = "Get a task"
							r.operationID = "getTask"
							r.operationGroup = ""
							r.pathPattern = "/api/v1/tasks/{number}"
							r.args = args
							r.count = 1
							return r, true
						case "PATCH":
							r.name = UpdateTaskOperation
							r.summary = "Update a task"
							r.operationID = "updateTask"
							r.operationGroup = ""
							r.pathPattern = "/api/v1/tasks/{number}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "a"

							if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'c': // Prefix: "ctivity"

								if l := len("ctivity"); len(elem) >= l && elem[0:l] == "ctivity" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ListTaskActivityOperation
										r.summary = "List task activity"
										r.operationID = "listTaskActivity"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/tasks/{number}/activity"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'g': // Prefix: "gent-conversations"

								if l := len("gent-conversations"); len(elem) >= l && elem[0:l] == "gent-conversations" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ListTaskAgentConversationsOperation
										r.summary = "List Agent conversations for the task timeline"
										r.operationID = "listTaskAgentConversations"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/tasks/{number}/agent-conversations"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'r': // Prefix: "rchive"

								if l := len("rchive"); len(elem) >= l && elem[0:l] == "rchive" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = ArchiveTaskOperation
										r.summary = "Archive a task"
										r.operationID = "archiveTask"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/tasks/{number}/archive"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 't': // Prefix: "ttachments"

								if l := len("ttachments"); len(elem) >= l && elem[0:l] == "ttachments" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch method {
									case "GET":
										r.name = ListTaskAttachmentsOperation
										r.summary = "List active Task attachments"
										r.operationID = "listTaskAttachments"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/tasks/{number}/attachments"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'u': // Prefix: "uploads"
										origElem := elem
										if l := len("uploads"); len(elem) >= l && elem[0:l] == "uploads" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch method {
											case "POST":
												r.name = CreateTaskAttachmentUploadOperation
												r.summary = "Create a private attachment upload session"
												r.operationID = "createTaskAttachmentUpload"
												r.operationGroup = ""
												r.pathPattern = "/api/v1/tasks/{number}/attachments/uploads"
												r.args = args
												r.count = 1
												return r, true
											default:
												return
											}
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "id"
											// Match until "/"
											idx := strings.IndexByte(elem, '/')
											if idx < 0 {
												idx = len(elem)
											}
											args[1] = elem[:idx]
											elem = elem[idx:]

											if len(elem) == 0 {
												break
											}
											switch elem[0] {
											case '/': // Prefix: "/co"

												if l := len("/co"); len(elem) >= l && elem[0:l] == "/co" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													break
												}
												switch elem[0] {
												case 'm': // Prefix: "mplete"

													if l := len("mplete"); len(elem) >= l && elem[0:l] == "mplete" {
														elem = elem[l:]
													} else {
														break
													}

													if len(elem) == 0 {
														// Leaf node.
														switch method {
														case "POST":
															r.name = CompleteTaskAttachmentUploadOperation
															r.summary = "Verify an uploaded object and create the Task attachment"
															r.operationID = "completeTaskAttachmentUpload"
															r.operationGroup = ""
															r.pathPattern = "/api/v1/tasks/{number}/attachments/uploads/{id}/complete"
															r.args = args
															r.count = 2
															return r, true
														default:
															return
														}
													}

												case 'n': // Prefix: "ntent"

													if l := len("ntent"); len(elem) >= l && elem[0:l] == "ntent" {
														elem = elem[l:]
													} else {
														break
													}

													if len(elem) == 0 {
														// Leaf node.
														switch method {
														case "PUT":
															r.name = UploadTaskAttachmentContentOperation
															r.summary = "Stream content into a Local storage upload session"
															r.operationID = "uploadTaskAttachmentContent"
															r.operationGroup = ""
															r.pathPattern = "/api/v1/tasks/{number}/attachments/uploads/{id}/content"
															r.args = args
															r.count = 2
															return r, true
														default:
															return
														}
													}

												}

											}

										}

										elem = origElem
									}
									// Param: "id"
									// Match until "/"
									idx := strings.IndexByte(elem, '/')
									if idx < 0 {
										idx = len(elem)
									}
									args[1] = elem[:idx]
									elem = elem[idx:]

									if len(elem) == 0 {
										switch method {
										case "DELETE":
											r.name = DeleteTaskAttachmentOperation
											r.summary = "Soft-delete a Task attachment"
											r.operationID = "deleteTaskAttachment"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/tasks/{number}/attachments/{id}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}
									switch elem[0] {
									case '/': // Prefix: "/content"

										if l := len("/content"); len(elem) >= l && elem[0:l] == "/content" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "GET":
												r.name = GetTaskAttachmentContentOperation
												r.summary = "Read authorized private attachment content"
												r.operationID = "getTaskAttachmentContent"
												r.operationGroup = ""
												r.pathPattern = "/api/v1/tasks/{number}/attachments/{id}/content"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

									}

								}

							}

						case 'c': // Prefix: "c"

							if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'l': // Prefix: "laim"

								if l := len("laim"); len(elem) >= l && elem[0:l] == "laim" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = ClaimTaskOperation
										r.summary = "Claim an eligible assigned task for this client session"
										r.operationID = "claimTask"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/tasks/{number}/claim"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'o': // Prefix: "omments"

								if l := len("omments"); len(elem) >= l && elem[0:l] == "omments" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch method {
									case "GET":
										r.name = ListTaskCommentsOperation
										r.summary = "List task comments"
										r.operationID = "listTaskComments"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/tasks/{number}/comments"
										r.args = args
										r.count = 1
										return r, true
									case "POST":
										r.name = CreateTaskCommentOperation
										r.summary = "Add a task comment"
										r.operationID = "createTaskComment"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/tasks/{number}/comments"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "id"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "DELETE":
											r.name = DeleteTaskCommentOperation
											r.summary = "Delete a task comment"
											r.operationID = "deleteTaskComment"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/tasks/{number}/comments/{id}"
											r.args = args
											r.count = 2
											return r, true
										case "PATCH":
											r.name = UpdateTaskCommentOperation
											r.summary = "Update a task comment"
											r.operationID = "updateTaskComment"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/tasks/{number}/comments/{id}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

								}

							case 'r': // Prefix: "riteria"

								if l := len("riteria"); len(elem) >= l && elem[0:l] == "riteria" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ListTaskCriteriaOperation
										r.summary = "List task acceptance criteria"
										r.operationID = "listTaskCriteria"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/tasks/{number}/criteria"
										r.args = args
										r.count = 1
										return r, true
									case "POST":
										r.name = CreateTaskCriterionOperation
										r.summary = "Create a task acceptance criterion"
										r.operationID = "createTaskCriterion"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/tasks/{number}/criteria"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						case 'r': // Prefix: "restore"

							if l := len("restore"); len(elem) >= l && elem[0:l] == "restore" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = RestoreTaskOperation
									r.summary = "Restore a task"
									r.operationID = "restoreTask"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/tasks/{number}/restore"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			case 'u': // Prefix: "users"

				if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = ListUsersOperation
						r.summary = "List users available for work assignment"
						r.operationID = "listUsers"
						r.operationGroup = ""
						r.pathPattern = "/api/v1/users"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			}

		}
	}
	return r, false
}
