// Code generated by ogen, DO NOT EDIT.
package api

type ActivateMilestoneRes interface {
	activateMilestoneRes()
}

type AddTaskClaimProgressRes interface {
	addTaskClaimProgressRes()
}

type AnswerTaskClaimQuestionRes interface {
	answerTaskClaimQuestionRes()
}

type ArchiveProjectRes interface {
	archiveProjectRes()
}

type ArchiveTaskRes interface {
	archiveTaskRes()
}

type AskTaskClaimQuestionRes interface {
	askTaskClaimQuestionRes()
}

type CancelMilestoneRes interface {
	cancelMilestoneRes()
}

type ClaimTaskRes interface {
	claimTaskRes()
}

type CompleteMilestoneRes interface {
	completeMilestoneRes()
}

type CreateAcceptanceCheckRes interface {
	createAcceptanceCheckRes()
}

type CreateLabelRes interface {
	createLabelRes()
}

type CreateMilestoneCriterionRes interface {
	createMilestoneCriterionRes()
}

type CreateMilestoneRes interface {
	createMilestoneRes()
}

type CreateProjectRes interface {
	createProjectRes()
}

type CreateTaskCommentRes interface {
	createTaskCommentRes()
}

type CreateTaskCriterionRes interface {
	createTaskCriterionRes()
}

type CreateTaskRes interface {
	createTaskRes()
}

type DeleteCriterionRes interface {
	deleteCriterionRes()
}

type DeleteLabelRes interface {
	deleteLabelRes()
}

type DeleteTaskCommentRes interface {
	deleteTaskCommentRes()
}

type ExtendTaskClaimRes interface {
	extendTaskClaimRes()
}

type GetCurrentPrincipalRes interface {
	getCurrentPrincipalRes()
}

type GetCurrentTaskClaimRes interface {
	getCurrentTaskClaimRes()
}

type GetProjectRes interface {
	getProjectRes()
}

type GetTaskClaimRes interface {
	getTaskClaimRes()
}

type GetTaskRes interface {
	getTaskRes()
}

type ListLabelsRes interface {
	listLabelsRes()
}

type ListMilestoneCriteriaRes interface {
	listMilestoneCriteriaRes()
}

type ListProjectsRes interface {
	listProjectsRes()
}

type ListTaskActivityRes interface {
	listTaskActivityRes()
}

type ListTaskAgentConversationsRes interface {
	listTaskAgentConversationsRes()
}

type ListTaskClaimMessagesRes interface {
	listTaskClaimMessagesRes()
}

type ListTaskCommentsRes interface {
	listTaskCommentsRes()
}

type ListTaskCriteriaRes interface {
	listTaskCriteriaRes()
}

type ListTasksRes interface {
	listTasksRes()
}

type ListUsersRes interface {
	listUsersRes()
}

type RecordTaskClaimAcceptanceCheckRes interface {
	recordTaskClaimAcceptanceCheckRes()
}

type ReleaseTaskClaimRes interface {
	releaseTaskClaimRes()
}

type ReopenMilestoneRes interface {
	reopenMilestoneRes()
}

type RestoreProjectRes interface {
	restoreProjectRes()
}

type RestoreTaskRes interface {
	restoreTaskRes()
}

type SubmitTaskClaimRes interface {
	submitTaskClaimRes()
}

type UpdateCriterionRes interface {
	updateCriterionRes()
}

type UpdateLabelRes interface {
	updateLabelRes()
}

type UpdateMilestoneRes interface {
	updateMilestoneRes()
}

type UpdateProjectRes interface {
	updateProjectRes()
}

type UpdateTaskCommentRes interface {
	updateTaskCommentRes()
}

type UpdateTaskRes interface {
	updateTaskRes()
}
