// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ActivateMilestone implements activateMilestone operation.
	//
	// Activate a planned milestone.
	//
	// POST /api/v1/projects/{number}/milestones/{id}/activate
	ActivateMilestone(ctx context.Context, params ActivateMilestoneParams) (ActivateMilestoneRes, error)
	// AddProjectMember implements addProjectMember operation.
	//
	// Add a Project member.
	//
	// POST /api/v1/projects/{number}/members
	AddProjectMember(ctx context.Context, req *ProjectMembershipCreate, params AddProjectMemberParams) (AddProjectMemberRes, error)
	// AddTaskClaimProgress implements addTaskClaimProgress operation.
	//
	// Add an Agent progress message.
	//
	// POST /api/v1/claims/{id}/progress
	AddTaskClaimProgress(ctx context.Context, req *TaskClaimAgentMessage, params AddTaskClaimProgressParams) (AddTaskClaimProgressRes, error)
	// AnswerTaskClaimQuestion implements answerTaskClaimQuestion operation.
	//
	// Answer the pending Agent question and resume the Claim.
	//
	// POST /api/v1/claims/{id}/answer
	AnswerTaskClaimQuestion(ctx context.Context, req *TaskClaimHumanAnswer, params AnswerTaskClaimQuestionParams) (AnswerTaskClaimQuestionRes, error)
	// ArchiveProject implements archiveProject operation.
	//
	// Archive a project.
	//
	// POST /api/v1/projects/{number}/archive
	ArchiveProject(ctx context.Context, params ArchiveProjectParams) (ArchiveProjectRes, error)
	// ArchiveTask implements archiveTask operation.
	//
	// Archive a task.
	//
	// POST /api/v1/tasks/{number}/archive
	ArchiveTask(ctx context.Context, params ArchiveTaskParams) (ArchiveTaskRes, error)
	// AskTaskClaimQuestion implements askTaskClaimQuestion operation.
	//
	// Ask a human question and pause the Claim.
	//
	// POST /api/v1/claims/{id}/ask
	AskTaskClaimQuestion(ctx context.Context, req *TaskClaimAgentMessage, params AskTaskClaimQuestionParams) (AskTaskClaimQuestionRes, error)
	// CancelMilestone implements cancelMilestone operation.
	//
	// Cancel a milestone.
	//
	// POST /api/v1/projects/{number}/milestones/{id}/cancel
	CancelMilestone(ctx context.Context, req OptLifecycleRequest, params CancelMilestoneParams) (CancelMilestoneRes, error)
	// ClaimTask implements claimTask operation.
	//
	// Claim an eligible assigned task for this client session.
	//
	// POST /api/v1/tasks/{number}/claim
	ClaimTask(ctx context.Context, req *TaskClaimSession, params ClaimTaskParams) (ClaimTaskRes, error)
	// CompleteMilestone implements completeMilestone operation.
	//
	// Complete a milestone.
	//
	// POST /api/v1/projects/{number}/milestones/{id}/complete
	CompleteMilestone(ctx context.Context, req OptLifecycleRequest, params CompleteMilestoneParams) (CompleteMilestoneRes, error)
	// CompleteTaskAttachmentUpload implements completeTaskAttachmentUpload operation.
	//
	// Verify an uploaded object and create the Task attachment.
	//
	// POST /api/v1/tasks/{number}/attachments/uploads/{id}/complete
	CompleteTaskAttachmentUpload(ctx context.Context, params CompleteTaskAttachmentUploadParams) (CompleteTaskAttachmentUploadRes, error)
	// CreateAcceptanceCheck implements createAcceptanceCheck operation.
	//
	// Record an immutable acceptance check.
	//
	// POST /api/v1/criteria/{id}/checks
	CreateAcceptanceCheck(ctx context.Context, req *AcceptanceCheckCreate, params CreateAcceptanceCheckParams) (CreateAcceptanceCheckRes, error)
	// CreateLabel implements createLabel operation.
	//
	// Create a label.
	//
	// POST /api/v1/labels
	CreateLabel(ctx context.Context, req *LabelWrite, params CreateLabelParams) (CreateLabelRes, error)
	// CreateMilestone implements createMilestone operation.
	//
	// Create a milestone.
	//
	// POST /api/v1/projects/{number}/milestones
	CreateMilestone(ctx context.Context, req *MilestoneCreate, params CreateMilestoneParams) (CreateMilestoneRes, error)
	// CreateMilestoneCriterion implements createMilestoneCriterion operation.
	//
	// Create a milestone acceptance criterion.
	//
	// POST /api/v1/projects/{number}/milestones/{id}/criteria
	CreateMilestoneCriterion(ctx context.Context, req *CriterionCreate, params CreateMilestoneCriterionParams) (CreateMilestoneCriterionRes, error)
	// CreateProject implements createProject operation.
	//
	// Create a project.
	//
	// POST /api/v1/projects
	CreateProject(ctx context.Context, req *ProjectCreate, params CreateProjectParams) (CreateProjectRes, error)
	// CreateTask implements createTask operation.
	//
	// Create a task.
	//
	// POST /api/v1/tasks
	CreateTask(ctx context.Context, req *TaskCreate, params CreateTaskParams) (CreateTaskRes, error)
	// CreateTaskAttachmentUpload implements createTaskAttachmentUpload operation.
	//
	// Create a private attachment upload session.
	//
	// POST /api/v1/tasks/{number}/attachments/uploads
	CreateTaskAttachmentUpload(ctx context.Context, req *TaskAttachmentUploadWrite, params CreateTaskAttachmentUploadParams) (CreateTaskAttachmentUploadRes, error)
	// CreateTaskComment implements createTaskComment operation.
	//
	// Add a task comment.
	//
	// POST /api/v1/tasks/{number}/comments
	CreateTaskComment(ctx context.Context, req *CommentCreateWrite, params CreateTaskCommentParams) (CreateTaskCommentRes, error)
	// CreateTaskCriterion implements createTaskCriterion operation.
	//
	// Create a task acceptance criterion.
	//
	// POST /api/v1/tasks/{number}/criteria
	CreateTaskCriterion(ctx context.Context, req *CriterionCreate, params CreateTaskCriterionParams) (CreateTaskCriterionRes, error)
	// DeleteCriterion implements deleteCriterion operation.
	//
	// Remove an acceptance criterion.
	//
	// DELETE /api/v1/criteria/{id}
	DeleteCriterion(ctx context.Context, req OptLifecycleRequest, params DeleteCriterionParams) (DeleteCriterionRes, error)
	// DeleteLabel implements deleteLabel operation.
	//
	// Delete a label.
	//
	// DELETE /api/v1/labels/{id}
	DeleteLabel(ctx context.Context, params DeleteLabelParams) (DeleteLabelRes, error)
	// DeleteTaskAttachment implements deleteTaskAttachment operation.
	//
	// Soft-delete a Task attachment.
	//
	// DELETE /api/v1/tasks/{number}/attachments/{id}
	DeleteTaskAttachment(ctx context.Context, params DeleteTaskAttachmentParams) (DeleteTaskAttachmentRes, error)
	// DeleteTaskComment implements deleteTaskComment operation.
	//
	// Delete a task comment.
	//
	// DELETE /api/v1/tasks/{number}/comments/{id}
	DeleteTaskComment(ctx context.Context, params DeleteTaskCommentParams) (DeleteTaskCommentRes, error)
	// ExtendTaskClaim implements extendTaskClaim operation.
	//
	// Extend an active Claim.
	//
	// POST /api/v1/claims/{id}/extend
	ExtendTaskClaim(ctx context.Context, req *TaskClaimSession, params ExtendTaskClaimParams) (ExtendTaskClaimRes, error)
	// GetAgentConversation implements getAgentConversation operation.
	//
	// Get an Agent conversation configuration.
	//
	// GET /api/v1/agent-conversations/{id}
	GetAgentConversation(ctx context.Context, params GetAgentConversationParams) (GetAgentConversationRes, error)
	// GetCurrentAgentConversationConfiguration implements getCurrentAgentConversationConfiguration operation.
	//
	// Get the conversation configuration bound to the authenticated Agent Run.
	//
	// GET /api/v1/agent-runs/current/conversation-configuration
	GetCurrentAgentConversationConfiguration(ctx context.Context) (GetCurrentAgentConversationConfigurationRes, error)
	// GetCurrentPrincipal implements getCurrentPrincipal operation.
	//
	// Get the authenticated principal.
	//
	// GET /api/v1/me
	GetCurrentPrincipal(ctx context.Context) (GetCurrentPrincipalRes, error)
	// GetCurrentTaskClaim implements getCurrentTaskClaim operation.
	//
	// Get the unfinished Claim owned by this client session.
	//
	// GET /api/v1/agent/claims/current
	GetCurrentTaskClaim(ctx context.Context, params GetCurrentTaskClaimParams) (GetCurrentTaskClaimRes, error)
	// GetProject implements getProject operation.
	//
	// Get a project and its work aggregate.
	//
	// GET /api/v1/projects/{number}
	GetProject(ctx context.Context, params GetProjectParams) (GetProjectRes, error)
	// GetTask implements getTask operation.
	//
	// Get a task.
	//
	// GET /api/v1/tasks/{number}
	GetTask(ctx context.Context, params GetTaskParams) (GetTaskRes, error)
	// GetTaskAttachmentContent implements getTaskAttachmentContent operation.
	//
	// Read authorized private attachment content.
	//
	// GET /api/v1/tasks/{number}/attachments/{id}/content
	GetTaskAttachmentContent(ctx context.Context, params GetTaskAttachmentContentParams) (GetTaskAttachmentContentRes, error)
	// GetTaskClaim implements getTaskClaim operation.
	//
	// Get a Claim.
	//
	// GET /api/v1/claims/{id}
	GetTaskClaim(ctx context.Context, params GetTaskClaimParams) (GetTaskClaimRes, error)
	// ListAgentConversations implements listAgentConversations operation.
	//
	// List visible Agent conversation configurations.
	//
	// GET /api/v1/agent-conversations
	ListAgentConversations(ctx context.Context) (ListAgentConversationsRes, error)
	// ListLabels implements listLabels operation.
	//
	// List labels.
	//
	// GET /api/v1/labels
	ListLabels(ctx context.Context, params ListLabelsParams) (ListLabelsRes, error)
	// ListMilestoneCriteria implements listMilestoneCriteria operation.
	//
	// List milestone acceptance criteria.
	//
	// GET /api/v1/projects/{number}/milestones/{id}/criteria
	ListMilestoneCriteria(ctx context.Context, params ListMilestoneCriteriaParams) (ListMilestoneCriteriaRes, error)
	// ListProjectMembers implements listProjectMembers operation.
	//
	// List Project members.
	//
	// GET /api/v1/projects/{number}/members
	ListProjectMembers(ctx context.Context, params ListProjectMembersParams) (ListProjectMembersRes, error)
	// ListProjects implements listProjects operation.
	//
	// List projects.
	//
	// GET /api/v1/projects
	ListProjects(ctx context.Context, params ListProjectsParams) (ListProjectsRes, error)
	// ListTaskActivity implements listTaskActivity operation.
	//
	// List task activity.
	//
	// GET /api/v1/tasks/{number}/activity
	ListTaskActivity(ctx context.Context, params ListTaskActivityParams) (ListTaskActivityRes, error)
	// ListTaskAgentConversations implements listTaskAgentConversations operation.
	//
	// List Agent conversations for the task timeline.
	//
	// GET /api/v1/tasks/{number}/agent-conversations
	ListTaskAgentConversations(ctx context.Context, params ListTaskAgentConversationsParams) (ListTaskAgentConversationsRes, error)
	// ListTaskAttachments implements listTaskAttachments operation.
	//
	// List active Task attachments.
	//
	// GET /api/v1/tasks/{number}/attachments
	ListTaskAttachments(ctx context.Context, params ListTaskAttachmentsParams) (ListTaskAttachmentsRes, error)
	// ListTaskClaimMessages implements listTaskClaimMessages operation.
	//
	// List the immutable Agent conversation for a Claim.
	//
	// GET /api/v1/claims/{id}/messages
	ListTaskClaimMessages(ctx context.Context, params ListTaskClaimMessagesParams) (ListTaskClaimMessagesRes, error)
	// ListTaskComments implements listTaskComments operation.
	//
	// List task comments.
	//
	// GET /api/v1/tasks/{number}/comments
	ListTaskComments(ctx context.Context, params ListTaskCommentsParams) (ListTaskCommentsRes, error)
	// ListTaskCriteria implements listTaskCriteria operation.
	//
	// List task acceptance criteria.
	//
	// GET /api/v1/tasks/{number}/criteria
	ListTaskCriteria(ctx context.Context, params ListTaskCriteriaParams) (ListTaskCriteriaRes, error)
	// ListTasks implements listTasks operation.
	//
	// List tasks.
	//
	// GET /api/v1/tasks
	ListTasks(ctx context.Context, params ListTasksParams) (ListTasksRes, error)
	// ListUsers implements listUsers operation.
	//
	// List users available for work assignment.
	//
	// GET /api/v1/users
	ListUsers(ctx context.Context, params ListUsersParams) (ListUsersRes, error)
	// RecordTaskClaimAcceptanceCheck implements recordTaskClaimAcceptanceCheck operation.
	//
	// Record an acceptance check owned by the active Claim.
	//
	// POST /api/v1/claims/{id}/criteria/{criterion_id}/checks
	RecordTaskClaimAcceptanceCheck(ctx context.Context, req *TaskClaimAcceptanceCheckCreate, params RecordTaskClaimAcceptanceCheckParams) (RecordTaskClaimAcceptanceCheckRes, error)
	// ReleaseTaskClaim implements releaseTaskClaim operation.
	//
	// Release a Claim.
	//
	// POST /api/v1/claims/{id}/release
	ReleaseTaskClaim(ctx context.Context, req *TaskClaimRelease, params ReleaseTaskClaimParams) (ReleaseTaskClaimRes, error)
	// RemoveProjectMember implements removeProjectMember operation.
	//
	// Remove a Project member.
	//
	// DELETE /api/v1/projects/{number}/members/{user_id}
	RemoveProjectMember(ctx context.Context, params RemoveProjectMemberParams) (RemoveProjectMemberRes, error)
	// ReopenMilestone implements reopenMilestone operation.
	//
	// Reopen a milestone.
	//
	// POST /api/v1/projects/{number}/milestones/{id}/reopen
	ReopenMilestone(ctx context.Context, req *LifecycleRequest, params ReopenMilestoneParams) (ReopenMilestoneRes, error)
	// RestoreProject implements restoreProject operation.
	//
	// Restore a project.
	//
	// POST /api/v1/projects/{number}/restore
	RestoreProject(ctx context.Context, params RestoreProjectParams) (RestoreProjectRes, error)
	// RestoreTask implements restoreTask operation.
	//
	// Restore a task.
	//
	// POST /api/v1/tasks/{number}/restore
	RestoreTask(ctx context.Context, params RestoreTaskParams) (RestoreTaskRes, error)
	// SubmitTaskClaim implements submitTaskClaim operation.
	//
	// Submit verified Agent work for human review.
	//
	// POST /api/v1/claims/{id}/submit
	SubmitTaskClaim(ctx context.Context, req *TaskClaimAgentMessage, params SubmitTaskClaimParams) (SubmitTaskClaimRes, error)
	// UpdateAgentConversation implements updateAgentConversation operation.
	//
	// Update an Agent conversation configuration.
	//
	// PATCH /api/v1/agent-conversations/{id}
	UpdateAgentConversation(ctx context.Context, req *AgentConversationPatch, params UpdateAgentConversationParams) (UpdateAgentConversationRes, error)
	// UpdateCriterion implements updateCriterion operation.
	//
	// Update an acceptance criterion.
	//
	// PATCH /api/v1/criteria/{id}
	UpdateCriterion(ctx context.Context, req *CriterionPatch, params UpdateCriterionParams) (UpdateCriterionRes, error)
	// UpdateCurrentAgentConversationConfiguration implements updateCurrentAgentConversationConfiguration operation.
	//
	// Update the conversation configuration bound to the authenticated Agent Run.
	//
	// PATCH /api/v1/agent-runs/current/conversation-configuration
	UpdateCurrentAgentConversationConfiguration(ctx context.Context, req *AgentConversationPatch, params UpdateCurrentAgentConversationConfigurationParams) (UpdateCurrentAgentConversationConfigurationRes, error)
	// UpdateLabel implements updateLabel operation.
	//
	// Rename a label.
	//
	// PATCH /api/v1/labels/{id}
	UpdateLabel(ctx context.Context, req *LabelWrite, params UpdateLabelParams) (UpdateLabelRes, error)
	// UpdateMilestone implements updateMilestone operation.
	//
	// Update a milestone.
	//
	// PATCH /api/v1/projects/{number}/milestones/{id}
	UpdateMilestone(ctx context.Context, req *MilestonePatch, params UpdateMilestoneParams) (UpdateMilestoneRes, error)
	// UpdateProject implements updateProject operation.
	//
	// Update a project.
	//
	// PATCH /api/v1/projects/{number}
	UpdateProject(ctx context.Context, req *ProjectPatch, params UpdateProjectParams) (UpdateProjectRes, error)
	// UpdateProjectMember implements updateProjectMember operation.
	//
	// Change a Project member role.
	//
	// PATCH /api/v1/projects/{number}/members/{user_id}
	UpdateProjectMember(ctx context.Context, req *ProjectMembershipPatch, params UpdateProjectMemberParams) (UpdateProjectMemberRes, error)
	// UpdateTask implements updateTask operation.
	//
	// Update a task.
	//
	// PATCH /api/v1/tasks/{number}
	UpdateTask(ctx context.Context, req *TaskPatch, params UpdateTaskParams) (UpdateTaskRes, error)
	// UpdateTaskComment implements updateTaskComment operation.
	//
	// Update a task comment.
	//
	// PATCH /api/v1/tasks/{number}/comments/{id}
	UpdateTaskComment(ctx context.Context, req *CommentUpdateWrite, params UpdateTaskCommentParams) (UpdateTaskCommentRes, error)
	// UploadTaskAttachmentContent implements uploadTaskAttachmentContent operation.
	//
	// Stream content into a Local storage upload session.
	//
	// PUT /api/v1/tasks/{number}/attachments/uploads/{id}/content
	UploadTaskAttachmentContent(ctx context.Context, req UploadTaskAttachmentContentReq, params UploadTaskAttachmentContentParams) (UploadTaskAttachmentContentRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
