// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	ActivateMilestoneOperation        OperationName = "ActivateMilestone"
	ArchiveProjectOperation           OperationName = "ArchiveProject"
	ArchiveTaskOperation              OperationName = "ArchiveTask"
	CancelMilestoneOperation          OperationName = "CancelMilestone"
	CompleteMilestoneOperation        OperationName = "CompleteMilestone"
	CreateAcceptanceCheckOperation    OperationName = "CreateAcceptanceCheck"
	CreateLabelOperation              OperationName = "CreateLabel"
	CreateMilestoneOperation          OperationName = "CreateMilestone"
	CreateMilestoneCriterionOperation OperationName = "CreateMilestoneCriterion"
	CreateProjectOperation            OperationName = "CreateProject"
	CreateTaskOperation               OperationName = "CreateTask"
	CreateTaskCommentOperation        OperationName = "CreateTaskComment"
	CreateTaskCriterionOperation      OperationName = "CreateTaskCriterion"
	DeleteCriterionOperation          OperationName = "DeleteCriterion"
	DeleteLabelOperation              OperationName = "DeleteLabel"
	DeleteTaskCommentOperation        OperationName = "DeleteTaskComment"
	GetCurrentPrincipalOperation      OperationName = "GetCurrentPrincipal"
	GetProjectOperation               OperationName = "GetProject"
	GetTaskOperation                  OperationName = "GetTask"
	ListLabelsOperation               OperationName = "ListLabels"
	ListMilestoneCriteriaOperation    OperationName = "ListMilestoneCriteria"
	ListProjectsOperation             OperationName = "ListProjects"
	ListTaskActivityOperation         OperationName = "ListTaskActivity"
	ListTaskCommentsOperation         OperationName = "ListTaskComments"
	ListTaskCriteriaOperation         OperationName = "ListTaskCriteria"
	ListTasksOperation                OperationName = "ListTasks"
	ListUsersOperation                OperationName = "ListUsers"
	ReopenMilestoneOperation          OperationName = "ReopenMilestone"
	RestoreProjectOperation           OperationName = "RestoreProject"
	RestoreTaskOperation              OperationName = "RestoreTask"
	UpdateCriterionOperation          OperationName = "UpdateCriterion"
	UpdateLabelOperation              OperationName = "UpdateLabel"
	UpdateMilestoneOperation          OperationName = "UpdateMilestone"
	UpdateProjectOperation            OperationName = "UpdateProject"
	UpdateTaskOperation               OperationName = "UpdateTask"
	UpdateTaskCommentOperation        OperationName = "UpdateTaskComment"
)
