package domain

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

// TaskStatus is the task's place in its lifecycle. Every status may move to
// every other status and there is no terminal state. Entering done is the
// one readiness gate: if the task defines acceptance criteria, their current
// revisions must all be passed or human-waived.
type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "todo"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusInReview   TaskStatus = "in_review"
	TaskStatusDone       TaskStatus = "done"
	TaskStatusCancelled  TaskStatus = "cancelled"
)

// Valid reports whether s is one of the five defined statuses.
func (s TaskStatus) Valid() bool {
	switch s {
	case TaskStatusTodo, TaskStatusInProgress, TaskStatusInReview, TaskStatusDone, TaskStatusCancelled:
		return true
	}
	return false
}

// TaskPriority is an ordinary priority label, not a scheduling constraint.
type TaskPriority string

const (
	TaskPriorityNone   TaskPriority = "none"
	TaskPriorityLow    TaskPriority = "low"
	TaskPriorityMedium TaskPriority = "medium"
	TaskPriorityHigh   TaskPriority = "high"
	TaskPriorityUrgent TaskPriority = "urgent"
)

// Valid reports whether p is one of the five defined priorities.
func (p TaskPriority) Valid() bool {
	switch p {
	case TaskPriorityNone, TaskPriorityLow, TaskPriorityMedium, TaskPriorityHigh, TaskPriorityUrgent:
		return true
	}
	return false
}

// Task is a unit of work. Number is a short, sequential, human-facing
// identifier ("look at 142") assigned once at creation and never reused —
// tasks are never hard-deleted (only archived, via ArchivedAt), and Number
// is generated by a database sequence that never steps backward, so the
// combination is enough to guarantee stability without extra bookkeeping.
//
// AssigneeID is nullable: unassigned is a normal, first-class state, not an
// error or a placeholder to fill in later.
type Task struct {
	ID          uuid.UUID
	Number      int64
	Title       string
	Description string
	Status      TaskStatus
	Priority    TaskPriority
	AssigneeID  *uuid.UUID
	CreatorID   uuid.UUID
	DueDate     *time.Time
	ProjectID   *uuid.UUID
	MilestoneID *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CompletedAt *time.Time
	ArchivedAt  *time.Time
}

// TaskCompletionReadiness is a snapshot taken while the task row is locked.
// A task with no active criteria remains intentionally lightweight and may be
// completed directly; once criteria exist, every active criterion is binding.
type TaskCompletionReadiness struct {
	ActiveCriteria      int
	UnsatisfiedCriteria int
}

// ValidateCompletion enforces the task's optional acceptance contract.
func (t Task) ValidateCompletion(readiness TaskCompletionReadiness) error {
	if readiness.ActiveCriteria > 0 && readiness.UnsatisfiedCriteria > 0 {
		return fmt.Errorf("%w: task acceptance is not satisfied", ErrConflict)
	}
	return nil
}

// TaskPatch is a partial update to a Task. Every field is optional; the
// *Set booleans distinguish "not provided, leave unchanged" from "provided
// as null, clear the value" for the nullable fields (AssigneeID, DueDate),
// which a plain pointer cannot: encoding/json sets a *T field to nil for
// both a missing key and an explicit JSON null. Title/Description/Status/
// Priority are never null-valued, so a plain pointer (nil = not provided) is
// enough for them.
type TaskPatch struct {
	Title       *string
	Description *string
	Status      *TaskStatus
	Priority    *TaskPriority

	AssigneeSet bool
	AssigneeID  *uuid.UUID

	DueDateSet bool
	DueDate    *time.Time

	LabelsSet bool
	LabelIDs  []uuid.UUID

	ProjectSet bool
	ProjectID  *uuid.UUID

	MilestoneSet bool
	MilestoneID  *uuid.UUID
}

// IsEmpty reports whether the patch changes nothing at all, in which case a
// store Update becomes a harmless no-op read rather than a write.
func (p TaskPatch) IsEmpty() bool {
	return p.Title == nil && p.Description == nil && p.Status == nil && p.Priority == nil &&
		!p.AssigneeSet && !p.DueDateSet && !p.LabelsSet && !p.ProjectSet && !p.MilestoneSet
}
