package domain

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

// TaskStatus is the compatibility representation retained during the additive
// migration window. New product behavior uses TaskPhase and TaskActivityState.
type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "todo"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusInReview   TaskStatus = "in_review"
	TaskStatusDone       TaskStatus = "done"
	TaskStatusCancelled  TaskStatus = "cancelled"
)

// Valid reports whether s is one of the five legacy statuses.
func (s TaskStatus) Valid() bool {
	switch s {
	case TaskStatusTodo, TaskStatusInProgress, TaskStatusInReview, TaskStatusDone, TaskStatusCancelled:
		return true
	}
	return false
}

// TaskPriority is an ordinary priority label, not a scheduling constraint.
type TaskPriority string

const (
	TaskPriorityNone   TaskPriority = "none"
	TaskPriorityLow    TaskPriority = "low"
	TaskPriorityMedium TaskPriority = "medium"
	TaskPriorityHigh   TaskPriority = "high"
	TaskPriorityUrgent TaskPriority = "urgent"
)

// Valid reports whether p is one of the five defined priorities.
func (p TaskPriority) Valid() bool {
	switch p {
	case TaskPriorityNone, TaskPriorityLow, TaskPriorityMedium, TaskPriorityHigh, TaskPriorityUrgent:
		return true
	}
	return false
}

// TaskExecutionMode is retained only for legacy-row migration. The target
// workflow gives authorized human and Agent actors equivalent capabilities.
type TaskExecutionMode string

const (
	TaskExecutionModeHumanOnly    TaskExecutionMode = "human_only"
	TaskExecutionModeAgentAllowed TaskExecutionMode = "agent_allowed"
)

func (m TaskExecutionMode) Valid() bool {
	switch m {
	case TaskExecutionModeHumanOnly, TaskExecutionModeAgentAllowed:
		return true
	}
	return false
}

// Task is a unit of work. Number is a short, sequential, human-facing
// identifier ("look at 142") assigned once at creation and never reused —
// tasks are never hard-deleted (only archived, via ArchivedAt), and Number
// is generated by a database sequence that never steps backward, so the
// combination is enough to guarantee stability without extra bookkeeping.
//
// ProjectID is required: Project is the task's durable work context.
// AssigneeID is nullable: unassigned is a normal, first-class state, not an
// error or a placeholder to fill in later.
type Task struct {
	ID                  uuid.UUID
	Number              int64
	Version             int64
	Title               string
	Context             string
	ExpectedResult      string
	Description         string
	Phase               TaskPhase
	Activity            TaskActivityState
	ReviewCycle         int64
	ActiveIssueThreadID *uuid.UUID
	MainThreadID        uuid.UUID
	// Status and ExecutionMode remain readable during the additive rollout.
	// New workflow commands use Phase and Activity exclusively.
	Status        TaskStatus
	Priority      TaskPriority
	ExecutionMode TaskExecutionMode
	AssigneeID    *uuid.UUID
	CreatorID     uuid.UUID
	StartDate     *time.Time
	DueDate       *time.Time
	ProjectID     uuid.UUID
	MilestoneID   *uuid.UUID
	ParentTaskID  *uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CompletedAt   *time.Time
	ArchivedAt    *time.Time
}

func (t Task) TargetLifecycle() TaskLifecycle {
	return TaskLifecycle{
		Phase: t.Phase, Activity: t.Activity, ReviewCycle: t.ReviewCycle,
	}
}

// TaskCompletionReadiness is a snapshot taken while the task row is locked.
// A task with no active criteria remains intentionally lightweight and may be
// completed directly; once criteria exist, every active criterion is binding.
type TaskCompletionReadiness struct {
	ActiveCriteria         int
	UnsatisfiedCriteria    int
	UnfinishedChildren     int
	UnfinishedDependencies int
}

// ValidateAcceptance checks only the explicit acceptance contract. Agent
// submission uses this gate because it moves work to in_review, not done.
func (r TaskCompletionReadiness) ValidateAcceptance() error {
	if r.ActiveCriteria > 0 && r.UnsatisfiedCriteria > 0 {
		return fmt.Errorf("%w: task acceptance is not satisfied", ErrConflict)
	}
	return nil
}

// ValidateCompletion enforces the task's optional acceptance contract and
// relationship readiness. Dependencies and children never prevent work from
// starting; they only prevent the task from entering done.
func (t Task) ValidateCompletion(readiness TaskCompletionReadiness) error {
	if err := readiness.ValidateAcceptance(); err != nil {
		return err
	}
	if readiness.UnfinishedChildren > 0 {
		return fmt.Errorf("%w: task has unfinished children", ErrConflict)
	}
	if readiness.UnfinishedDependencies > 0 {
		return fmt.Errorf("%w: task has unfinished dependencies", ErrConflict)
	}
	return nil
}

// ValidateSchedule keeps a task's explicit range coherent. Either endpoint may
// be absent: a due-only task renders as a marker, while an entirely unscheduled
// task remains outside the timeline.
func ValidateSchedule(startDate, dueDate *time.Time) error {
	if startDate != nil && dueDate != nil && startDate.After(*dueDate) {
		return fmt.Errorf("%w: task start date must not follow due date", ErrInvalidInput)
	}
	return nil
}

// TaskPatch is a partial update to a Task. Every field is optional; the
// *Set booleans distinguish "not provided, leave unchanged" from "provided
// as null, clear the value" for the nullable fields (AssigneeID, DueDate),
// which a plain pointer cannot: encoding/json sets a *T field to nil for
// both a missing key and an explicit JSON null. Title, Description, and
// Priority are never null-valued, so a plain pointer (nil = not provided) is
// enough for them. Status and ExecutionMode remain internal compatibility
// inputs until the contract migration; /api/v1 does not expose them.
type TaskPatch struct {
	Title          *string
	Context        *string
	ExpectedResult *string
	Description    *string
	Status         *TaskStatus
	Priority       *TaskPriority
	ExecutionMode  *TaskExecutionMode

	AssigneeSet bool
	AssigneeID  *uuid.UUID

	DueDateSet bool
	DueDate    *time.Time

	StartDateSet bool
	StartDate    *time.Time

	LabelsSet bool
	LabelIDs  []uuid.UUID

	ProjectSet bool
	ProjectID  *uuid.UUID

	MilestoneSet bool
	MilestoneID  *uuid.UUID

	ParentSet    bool
	ParentTaskID *uuid.UUID

	DependenciesSet bool
	DependencyIDs   []uuid.UUID

	ScheduleShiftDays *int
}

// IsEmpty reports whether the patch changes nothing at all, in which case a
// store Update becomes a harmless no-op read rather than a write.
func (p TaskPatch) IsEmpty() bool {
	return p.Title == nil && p.Context == nil && p.ExpectedResult == nil &&
		p.Description == nil && p.Status == nil && p.Priority == nil &&
		p.ExecutionMode == nil &&
		!p.AssigneeSet && !p.StartDateSet && !p.DueDateSet && !p.LabelsSet &&
		!p.ProjectSet && !p.MilestoneSet && !p.ParentSet && !p.DependenciesSet &&
		p.ScheduleShiftDays == nil
}
